/**
 * The anchor contract (plan §5).
 *
 * The problem this solves: the trace is generated by a TypeScript generator, but
 * the student reads Python, Java or C++. There is no meaningful relationship
 * between "line 42 of pair-sum.ts" and "line 17 of pair_sum.py", so the obvious
 * approach — putting a literal `line: 42` in each frame — is meaningless the
 * moment you add a second language.
 *
 * The fix is to key on *semantics* instead of *positions*. A frame says
 * `anchor: 'compare'`. Every language version of the algorithm marks the
 * corresponding source line with a trailing `@anchor compare` comment, and the
 * parser below turns those markers into line ranges. So:
 *
 *   - the highlight follows the code, because it is derived from the code;
 *   - it cannot drift, because moving a line moves its marker with it;
 *   - it is the *same* anchor in every language, so switching tabs shows the
 *     student `if s < target:` next to `if (sum < target)` and they can see
 *     that those are one step.
 *
 * The markers live inside the source as ordinary comments, using whichever
 * comment syntax that language has (`#` in Python, `//` in JS/Java/C++). One
 * convention, four languages.
 */

export const LANGS = ['javascript', 'python', 'java', 'cpp'] as const;
export type Lang = (typeof LANGS)[number];

export const LANG_LABEL: Record<Lang, string> = {
  javascript: 'JavaScript',
  python: 'Python',
  java: 'Java',
  cpp: 'C++',
};

/** Short labels for compact UI, and the shiki grammar id per language. */
export const LANG_META: Record<Lang, { short: string; grammar: string }> = {
  javascript: { short: 'JS', grammar: 'javascript' },
  python: { short: 'PY', grammar: 'python' },
  java: { short: 'JAVA', grammar: 'java' },
  cpp: { short: 'C++', grammar: 'cpp' },
};

const ANCHOR_RE = /@anchor\s+([A-Za-z_][A-Za-z0-9_-]*)/g;

/**
 * The same marker, for removal: a trailing comment that consists only of the
 * marker, plus the padding that aligned it. The lookbehind requires a preceding
 * space so a bare `@anchor x` inside a string literal is left alone rather than
 * silently deleted from someone's code.
 */
/**
 * A trailing comment consisting only of one *or more* markers.
 *
 * One pass, not a loop: `(?:@anchor NAME)+` matches `// @anchor match  @anchor
 * mismatch` whole, because the repetition is of the *whole* `marker + name` unit
 * rather than of bare names. A loop over a single-marker regex looks equivalent
 * and silently does nothing — the first pass cannot match, so the loop exits at
 * iteration zero having removed nothing.
 */
const ANCHOR_STRIP_RE = /[ \t]*(?:\/\/|#)[ \t]*(?:@anchor[ \t]*[A-Za-z_][A-Za-z0-9_-]*[ \t]*)+$/;

/**
 * Remove the `@anchor` markers from a source listing, for display.
 *
 * The markers are load-bearing metadata — they are how the highlight finds its
 * line — but they are not something a student should read. Left in, the
 * right-alignment padding pushes every annotated line well past the width of the
 * code panel, so the interesting part of the line scrolls off the right edge.
 * Stripping them makes the listing look like the textbook version, and the panel
 * already names the anchor ("line 9 · compare") directly underneath.
 *
 * Line count and line numbers are preserved exactly: the marker is deleted, the
 * line is not. That is what keeps `anchor → line` valid for the display source.
 */
export function stripMarkers(source: string): string {
  return source
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.replace(ANCHOR_STRIP_RE, '').replace(/[ \t]+$/, ''))
    .join('\n');
}

/** A span of source lines, 1-based inclusive, as the editor displays them. */
export interface LineRange {
  start: number;
  end: number;
}

export interface ParsedCode {
  lang: Lang;
  source: string;
  lines: string[];
  /** anchor name → the line(s) carrying its marker. */
  anchors: Record<string, LineRange>;
  /** The @anchor markers, with the line text, for drift tests and tooltips. */
  markerLines: Record<string, { line: number; text: string }>;
}

export function parseCode(lang: Lang, source: string): ParsedCode {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const anchors: Record<string, LineRange> = {};
  const markerLines: Record<string, { line: number; text: string }> = {};

  for (let i = 0; i < lines.length; i++) {
    const text = lines[i] ?? '';

    /*
     * A line may carry *several* anchors, and that is a real case rather than a
     * convenience. Edit distance's cost line is one line with two outcomes —
     * `const cost = a[i-1] === b[j-1] ? 0 : 1` is both the "match" step and the
     * "mismatch" step — and the two deserve different explanations while pointing
     * at the same source. Reading only the first marker made the second anchor
     * unresolvable, so the contract test failed on a module that was correct.
     */
    ANCHOR_RE.lastIndex = 0;
    let m = ANCHOR_RE.exec(text);
    while (m) {
      const name = m[1];
      if (name !== undefined && !(name in anchors)) {
        const line = i + 1;
        anchors[name] = { start: line, end: line };
        markerLines[name] = { line, text: text.trim() };
      }
      m = ANCHOR_RE.exec(text);
    }
  }

  return { lang, source, lines, anchors, markerLines };
}

/** Every anchor a trace can reach, in first-seen order. */
export function anchorsInTrace(frames: ReadonlyArray<{ anchor: string }>): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const f of frames) {
    if (!seen.has(f.anchor)) {
      seen.add(f.anchor);
      out.push(f.anchor);
    }
  }
  return out;
}

/** Resolve an anchor to a line range, or null if the lesson has no such line. */
export function resolveAnchor(parsed: ParsedCode, anchor: string | undefined): LineRange | null {
  if (!anchor) return null;
  return parsed.anchors[anchor] ?? null;
}

/* ------------------------------------------------------------------ *
 * The Lesson type — what a student actually reads
 * ------------------------------------------------------------------ */

export interface Lesson {
  /**
   * Clean, idiomatic, *standalone* implementations, one per language.
   *
   * These are deliberately NOT the generator source. A generator threaded with
   * `yield { kind: 'array', highlight: { ... } }` is unreadable and is not what
   * anyone writes; showing it would teach the visualiser, not the algorithm.
   * The generator is an internal authoring device. This is also why the
   * translation parity test (plan §5.4) is not optional — the shown code is a
   * separate artefact from the thing that produces the animation, and an
   * independent check is what keeps them honest.
   */
  code: Record<Lang, string>;
  /**
   * One plain-English explanation per anchor, per language.
   *
   * Keyed by anchor, in the UI language. This is the text the student reads
   * directly beneath the highlighted line, so it should say what the line does
   * *to the data structure*, not restate the line. "Moves `left` one step
   * right, so the next sum uses a bigger left value" — not "increments left".
   */
  notes: Record<Lang, Record<string, string>>;
  /** Function/method name per language, used by the verification harness to call it. */
  entry: Record<Lang, string>;
  /**
   * Which named argument-adapter the verification driver should use to turn the
   * JSON args into a language-native value. Not shown to students, and only
   * read by `tools/verify` — a dev-time Node harness that never ships.
   *
   * By name rather than by source, so the handful of adapters that 90% of
   * algorithms need are written once per language instead of 56 times:
   *
   *   `'auto'`  one sequence/scalar arg, element type inferred from the JSON
   *             (`int[]`, `double[]`, `String[]`, `int`, `String`, ...)
   *   `'graph'` the standard node/edge graph shape
   *   `'tree'`  a plain array of values, treated as a BST insertion sequence
   */
  glue: Record<Lang, GlueName>;
}

export const GLUE_NAMES = ['auto', 'graph', 'tree', 'words'] as const;
export type GlueName = (typeof GLUE_NAMES)[number];

/**
 * Transpose an anchor-keyed note table into the language-keyed shape `Lesson`
 * requires.
 *
 * Notes are *authored* anchor-first on purpose:
 *
 *   ```ts
 *   const NOTES = {
 *     compare: { javascript: '…', python: '…', java: '…', cpp: '…' },
 *   };
 *   ```
 *
 * so the four languages sit side by side and you can read them as a
 * translation set. Writing it the other way round — four blocks of eight long
 * strings — makes it impossible to check that a language's `swap` note actually
 * describes its own `swap` line. So the data is authored for humans and
 * transposed here, at the type level, with no runtime surprises.
 */
export function byLanguage<T>(
  anchorFirst: Record<string, Partial<Record<Lang, T>>>,
): Record<Lang, Record<string, T>> {
  const out = {} as Record<Lang, Record<string, T>>;
  for (const lang of LANGS) {
    const perLang: Record<string, T> = {};
    for (const [anchor, perLanguage] of Object.entries(anchorFirst)) {
      const value = perLanguage[lang];
      // A missing translation is a hard error rather than a silent blank in the
      // UI: a student switching to Java and finding no explanation is a bug, and
      // the contract test would not otherwise see it until they clicked.
      if (value === undefined) {
        throw new Error(`missing ${lang} text for anchor "${anchor}"`);
      }
      perLang[anchor] = value;
    }
    out[lang] = perLang;
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * Verification contract (plan §5.4)
 * ------------------------------------------------------------------ */

export type FormatResult = (result: unknown) => string;
