import type { CatalogEntry } from './catalog-types.ts';
import { CATEGORIES, type Category } from './types.ts';

export type { CatalogEntry };

/**
 * The navigation index.
 *
 * Pure data: no generators, no lesson source strings, no imports of the
 * algorithm modules themselves. That is the entire point. The sidebar renders
 * from this, so opening the app costs a few kilobytes instead of dragging 50+
 * generators and 200+ code listings into the initial bundle. The selected
 * algorithm's module is then fetched with a dynamic `import()`.
 *
 * GENERATED by `npm run gen:catalog` (tools/genCatalog.ts) from the modules' own
 * metadata, because a hand-maintained duplicate of six fields per algorithm is a
 * duplicate that will drift. `contract.test.ts` asserts the two agree, so a
 * forgotten regeneration is a failing test rather than a stale sidebar.
 *
 * The one thing that is *not* generated from the modules is the search
 * vocabulary — `tags` and `aka`. Those are the words a student would actually
 * type ("divide and conquer", "nlogn", "tortoise and hare"), and no amount of
 * reading a module tells you them. They live in `EXTRA` in the generator.
 *
 * Layout of an entry: category order first (the curriculum order, not
 * alphabetical — a student should meet bubble sort before quicksort), then by
 * title within the category.
 */

export const CATALOG: CatalogEntry[] = [
  {
    id: 'bubble-sort',
    title: 'Bubble Sort',
    category: 'sorting',
    summary:
      'Repeatedly swap adjacent pairs that are out of order, until a whole pass finds nothing to fix.',
    viewport: 'array',
    level: 'intro',
    tags: ['quadratic'],
    aka: ['sinking sort', 'exchange sort'],
  },
  {
    id: 'counting-sort',
    title: 'Counting Sort',
    category: 'sorting',
    summary:
      'Tabulate how many times each value occurs in a row indexed by value, turn the tallies into running totals, and write every value into the slot its total names.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['non-comparative', 'linear in n + k', 'stable', 'integers only', 'k can dominate'],
    aka: ['frequency sort', 'non comparison sort', 'prefix sums', 'linear time sort'],
  },
  {
    id: 'heap-sort',
    title: 'Heap Sort',
    category: 'sorting',
    summary:
      'Build a max-heap in the array itself, then repeatedly park the root at the far end and sift the replacement back down.',
    viewport: 'array',
    level: 'advanced',
    tags: ['divide and conquer', 'heap', 'guaranteed n log n', 'no recursion'],
    aka: ['heapsort', 'in place', 'worst case O(nlogn)'],
  },
  {
    id: 'insertion-sort',
    title: 'Insertion Sort',
    category: 'sorting',
    summary:
      'Grow a sorted prefix one element at a time, sliding every bigger value in that prefix one place to the right.',
    viewport: 'array',
    level: 'intro',
    tags: ['quadratic', 'online', 'adaptive'],
    aka: ['insort', 'online sort'],
  },
  {
    id: 'merge-sort',
    title: 'Merge Sort',
    category: 'sorting',
    summary:
      'Split the array in half, sort each half recursively, then interleave the two sorted runs into a shared auxiliary buffer.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['divide and conquer', 'guaranteed n log n', 'external sort'],
    aka: ['mergesort', 'divide and conquer', 'stable sort'],
  },
  {
    id: 'quick-sort',
    title: 'Quick Sort',
    category: 'sorting',
    summary:
      'Partition around a pivot so everything smaller ends up left of it, then sort the two halves independently.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['divide and conquer', 'lomuto', 'in place', 'quadratic worst case'],
    aka: ['quicksort', 'divide and conquer', 'partition'],
  },
  {
    id: 'radix-sort',
    title: 'Radix Sort (LSD)',
    category: 'sorting',
    summary:
      'Counting sort by the units digit, then by the tens digit, then by the hundreds digit: one stable pass per place value, from the least significant digit up.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['non-comparative', 'LSD', 'k is always 10', 'stable passes', 'integers only'],
    aka: ['lsd', 'least significant digit', 'non comparison sort', 'stable sort by digit'],
  },
  {
    id: 'selection-sort',
    title: 'Selection Sort',
    category: 'sorting',
    summary:
      'Scan the unsorted region for its smallest value, then swap that value into the first free position.',
    viewport: 'array',
    level: 'intro',
    tags: ['quadratic', 'minimum writes', 'exchange sort'],
    aka: ['sel sort'],
  },
  {
    id: 'shell-sort',
    title: 'Shell Sort',
    category: 'sorting',
    summary:
      'Insertion sort run repeatedly with a shrinking gap, so big values can move a long way in very few writes.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['quadratic', 'gap sequence', 'exchange sort', 'adaptive'],
    aka: ['shellsort', 'gap sort', 'diminishing increments'],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    category: 'searching',
    summary:
      'Probe the middle of the remaining range, then discard the half that cannot hold the target.',
    viewport: 'array',
    level: 'intro',
    tags: ['sorted input', 'logarithmic', 'divide and conquer'],
    aka: ['binsearch', 'halving', 'logarithmic'],
  },
  {
    id: 'exponential-search',
    title: 'Exponential Search',
    category: 'searching',
    summary:
      'Double a bound until it is past the target, then binary search only the window the doubling proved the answer lies in.',
    viewport: 'array',
    level: 'advanced',
    tags: ['sorted input', 'unbounded input', 'log of the answer'],
    aka: ['doubling search', 'galloping'],
  },
  {
    id: 'jump-search',
    title: 'Jump Search',
    category: 'searching',
    summary:
      'Compare only the last cell of each √n-sized block to skip whole blocks, then linearly scan the one block that could hold the target.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['sorted input', 'sqrt decomposition', 'branch friendly'],
    aka: ['block search', 'sqrt decomposition'],
  },
  {
    id: 'linear-search',
    title: 'Linear Search',
    category: 'searching',
    summary:
      'Walk the array from one end to the other, comparing each value with the target until they match or the array runs out.',
    viewport: 'array',
    level: 'intro',
    tags: ['unsorted', 'no precondition', 'single lookup'],
    aka: ['sequential search', 'brute force'],
  },
  {
    id: 'lower-bound',
    title: 'Lower Bound',
    category: 'searching',
    summary:
      'Binary search that never looks for equality — it halves the window until one index is left, and that index is the first value at least the target.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['sorted input', 'insertion point', 'logarithmic', 'no failure case'],
    aka: ['bisect', 'first index at least', 'partition point'],
  },
  {
    id: 'search-rotated',
    title: 'Search Rotated Array',
    category: 'searching',
    summary:
      'Binary search on a sorted-then-rotated array, identifying which half of the window is still in order and discarding the other.',
    viewport: 'array',
    level: 'advanced',
    tags: ['sorted then rotated', 'logarithmic', 'no index needed'],
    aka: ['rotated sorted', 'unknown pivot'],
  },
  {
    id: 'container-most-water',
    title: 'Container With Most Water',
    category: 'two-pointers',
    summary:
      'Squeeze two pointers in from the ends of a list of wall heights, measure the rectangle the water would fill, and retire whichever wall is shorter — the one that can no longer be part of anything better.',
    viewport: 'array',
    level: 'intro',
    tags: ['read-only', 'greedy elimination', 'no extra space', 'works unsorted'],
    aka: ['max area', 'two pointers'],
  },
  {
    id: 'dutch-national-flag',
    title: 'Dutch National Flag',
    category: 'two-pointers',
    summary:
      'One pass, three cursors: settle a 0 at the front, a 2 at the back, and a 1 where it already stands, never letting the cursor that is inspecting advance past a value a swap has just dragged onto it.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['one pass', 'three pointers', 'no extra space', 'not stable'],
    aka: ['sort colors', 'sort colours', 'three way partition', '3 way partition', 'one pass'],
  },
  {
    id: 'pair-sum',
    title: 'Pair Sum',
    category: 'two-pointers',
    summary:
      'Walk two pointers in from the ends of a sorted array, adding them up and throwing away whichever one could not possibly be part of a pair that hits the target.',
    viewport: 'array',
    level: 'intro',
    tags: ['sorted input', 'no extra space', 'returns indices', 'sentinel for not-found'],
    aka: ['two sum', 'sorted two pointers'],
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    category: 'two-pointers',
    summary:
      'Walk two cursors in from the ends of a skyline and settle the column behind whichever running maximum is smaller, because that ceiling is already the tallest one the column can ever see.',
    viewport: 'array',
    level: 'intro',
    tags: ['read-only', 'no extra space', 'greedy elimination', 'works unsorted'],
    aka: ['rain water', 'water trapping', 'two pointers', 'max left max right'],
  },
  {
    id: 'valid-palindrome',
    title: 'Valid Palindrome',
    category: 'two-pointers',
    summary:
      'Walk two pointers in from the ends of a string, step over everything that is not a letter or a digit, fold away case, and stop the first time the two ends disagree.',
    viewport: 'array',
    level: 'intro',
    tags: ['read-only', 'no extra space', 'early exit', 'case insensitive'],
    aka: ['palindrome', 'in place'],
  },
  {
    id: 'kadane',
    title: "Kadane's Algorithm",
    category: 'sliding-window',
    summary:
      'Scan left to right keeping the largest sum of any subarray that ends at the current position, throwing the running window away entirely the moment its sum turns negative.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['single pass', 'no extra space', 'returns a range', 'negative numbers'],
    aka: ['max subarray', 'prefix minimum'],
  },
  {
    id: 'longest-repeating-replacement',
    title: 'Longest Repeating Character Replacement',
    category: 'sliding-window',
    summary:
      'Slide a window along the string and keep the longest one that can be turned into a single repeated character within a budget of k replacements, using a most-frequent-character count that is allowed to go stale.',
    viewport: 'array',
    level: 'advanced',
    tags: [
      'single pass',
      'approximate matching',
      'stale record trick',
      'no extra copy of the input',
    ],
    aka: ['character replacement', 'sliding window'],
  },
  {
    id: 'longest-substring',
    title: 'Longest Substring Without Repeating Characters',
    category: 'sliding-window',
    summary:
      'Slide a window over the string, remembering where each character was last seen, and when a repeat turns up jump the left edge straight past the earlier copy instead of creeping forward one step at a time.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['single pass', 'no extra copy of the input', 'amortised O(1) per character'],
    aka: ['longest substring without repeating', 'sliding window'],
  },
  {
    id: 'min-window-substring',
    title: 'Minimum Window Substring',
    category: 'sliding-window',
    summary:
      'Grow a window one character at a time from the right, and the moment it contains every character the pattern needs, push the left edge in as far as it will go before letting the right edge move again.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['single pass', 'unordered pattern', 'returns a range', 'empty string for not-found'],
    aka: ['smallest window', 'sliding window'],
  },
  {
    id: 'activity-selection',
    title: 'Activity Selection',
    category: 'greedy',
    summary:
      'Take the interval that finishes earliest, then take each later interval that starts at or after the finish of the last one taken — a greedy whose exchange argument is one sentence long and needs no dynamic programming.',
    viewport: 'array',
    level: 'intro',
    tags: ['read-only', 'no extra space', 'pre-sorted input', 'greedy is provably optimal'],
    aka: ['interval scheduling', 'greedy', 'earliest finish'],
  },
  {
    id: 'gas-station',
    title: 'Gas Station',
    category: 'greedy',
    summary:
      'One pass with two running sums: a tank that restarts whenever it goes negative, and a total that never does — and only the total decides whether a start exists at all.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['read-only', 'no extra space', 'returns -1 when impossible', 'bulk elimination'],
    aka: ['gas', 'greedy', 'circular'],
  },
  {
    id: 'jump-game-2',
    title: 'Jump Game II',
    category: 'greedy',
    summary:
      'Sweep a single "farthest reachable" boundary forwards across the array, and count how many times it has to be committed before the last cell is inside it — a breadth-first search with the queue flattened into two integers.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['read-only', 'no extra space', 'returns -1 for unreachable', 'BFS layer greedy'],
    aka: ['jump game', 'greedy', 'fewest jumps'],
  },
  {
    id: 'knapsack',
    title: '0/1 Knapsack',
    category: 'dynamic-programming',
    summary:
      'Fill a table of "best value using the items above me and at most this capacity", taking the better of the cell above and the cell diagonally up-left.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['table', '0/1 choice', 'capacity', 'provenance tags', 'quadratic'],
    aka: ['0/1 knapsack', 'dp', 'value per weight'],
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    category: 'dynamic-programming',
    summary:
      'Fill a table of "fewest coins to make this amount using the coins in the rows above me", reading leftwards so a coin can be reused.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['table', 'unbounded', 'sentinel', 'quadratic'],
    aka: ['minimum coins', 'dp', 'unbounded'],
  },
  {
    id: 'edit-distance',
    title: 'Edit Distance',
    category: 'dynamic-programming',
    summary:
      'Turn two strings into each other for the fewest single-character insertions, deletions and substitutions, and record which edit each cell paid for.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['table', 'strings', 'edit script', 'symmetric'],
    aka: ['levenshtein', 'dp', 'distance'],
  },
  {
    id: 'fibonacci',
    title: 'Fibonacci',
    category: 'dynamic-programming',
    summary:
      'Compute each subproblem once by remembering the answers, then compute the same sequence again in increasing order and watch the two agree.',
    viewport: 'grid',
    level: 'intro',
    tags: ['memoisation', 'tabulation', 'top-down', 'bottom-up', 'recursion'],
    aka: ['fib', 'memoisation', 'tabulation', 'naive recursion'],
  },
  {
    id: 'lcs',
    title: 'Longest Common Subsequence',
    category: 'dynamic-programming',
    summary:
      'Build a table of how much each pair of prefixes shares, then walk it backwards to recover the shared sequence itself.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['table', 'strings', 'reconstruction', 'quadratic'],
    aka: ['longest common subsequence', 'dp', 'string'],
  },
  {
    id: 'lis',
    title: 'Longest Increasing Subsequence',
    category: 'dynamic-programming',
    summary:
      'Keep a sorted frontier of the smallest possible tail for every achievable run length, binary search where the next value belongs, and link each element to its predecessor.',
    viewport: 'array',
    level: 'advanced',
    tags: ['binary search', 'reconstruction', 'frontier', 'n log n'],
    aka: ['longest increasing subsequence', 'dp', 'tails'],
  },
  {
    id: 'rod-cutting',
    title: 'Rod Cutting',
    category: 'dynamic-programming',
    summary:
      'Split a rod into priced pieces for the maximum revenue, tracking for every rod length and every piece budget the best revenue found so far.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['table', 'unbounded', 'optimisation', 'quadratic'],
    aka: ['rod cut', 'dp', 'unbounded'],
  },
  {
    id: 'detect-cycle',
    title: 'Detect a Cycle (Floyd)',
    category: 'linked-lists',
    summary:
      'Walk two cursors at different speeds. If the fast one falls off the end there is no cycle; if they meet, they must be on a ring.',
    viewport: 'linked',
    level: 'intermediate',
    tags: ['two pointers', 'O(1) space', 'read-only safe', 'no allocation'],
    aka: ['floyd', 'tortoise and hare', 'linked list cycle'],
  },
  {
    id: 'merge-two-sorted',
    title: 'Merge Two Sorted Lists',
    category: 'linked-lists',
    summary:
      'Repeatedly take the smaller of the two heads and link it on. Because both inputs are already sorted, that head is always the smallest value left anywhere.',
    viewport: 'linked',
    level: 'intro',
    tags: ['linear', 'two pointers', 'sorted input', 'allocates only the prefix'],
    aka: ['merge lists', 'linked list'],
  },
  {
    id: 'reverse-list',
    title: 'Reverse a Linked List',
    category: 'linked-lists',
    summary:
      'Walk the list with two cursors and repoint every `next` field backwards, so the nodes never move and nothing is copied.',
    viewport: 'linked',
    level: 'intro',
    tags: ['pointer surgery', 'no allocation', 'iterative', 'O(1) space'],
    aka: ['linked list reversal', 'pointer rewiring'],
  },
  {
    id: 'balanced-brackets',
    title: 'Balanced Brackets',
    category: 'stacks-queues',
    summary:
      'Push every opener, and require each closer to match the top of the stack exactly. Balanced means the stack ends empty.',
    viewport: 'linear',
    level: 'intro',
    tags: ['O(1) per character', 'nesting', 'early exit', 'stack depth is the space cost'],
    aka: ['valid parentheses', 'stack'],
  },
  {
    id: 'valid-postfix',
    title: 'Evaluate a Postfix Expression',
    category: 'stacks-queues',
    summary:
      'Read the expression left to right: a number goes on the stack, an operator takes the top two and puts their result back. One value left at the end means it was well formed.',
    viewport: 'linear',
    level: 'intermediate',
    tags: ['no parentheses', 'single pass', 'validated', 'stack machine'],
    aka: ['postfix', 'rpn', 'stack'],
  },
  {
    id: 'largest-rectangle',
    title: 'Largest Rectangle in a Histogram',
    category: 'stacks-queues',
    summary:
      'Keep a non-decreasing stack of candidate heights. A shorter bar closes off the stack top, whose widest rectangle runs from just after the new stack top to the bar before the current one — and a zero-height sentinel at the end closes off everything that is left.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['monotonic stack', 'one pass', 'amortised O(1)', 'sentinel bar', 'histogram'],
    aka: ['largest rectangle in histogram', 'histogram', 'maximal rectangle', 'monotonic stack'],
  },
  {
    id: 'min-stack',
    title: 'Min Stack',
    category: 'stacks-queues',
    summary:
      'Keep a second stack of running minima, one entry per depth, so that after any pop the smallest remaining value is the top of that stack.',
    viewport: 'linear',
    level: 'intermediate',
    tags: ['O(1) getMin', 'two stacks', 'pushdown automaton', 'space for speed'],
    aka: ['stack with min', 'auxiliary stack'],
  },
  {
    id: 'next-greater-element',
    title: 'Next Greater Element',
    category: 'stacks-queues',
    summary:
      'Walk left to right with a stack of unanswered indices in non-increasing order; every value that beats the top of the stack answers it, and whatever is left at the end has no greater element.',
    viewport: 'array',
    level: 'intermediate',
    tags: ['monotonic stack', 'one pass', 'amortised O(1)', 'suffix query', 'sentinel -1'],
    aka: ['next greater', 'next larger element', 'monotonic stack', 'stack'],
  },
  {
    id: 'sliding-window-max',
    title: 'Sliding Window Maximum',
    category: 'stacks-queues',
    summary:
      "Keep a decreasing deque of candidate maxima. A new value throws away every smaller value behind it, and the front of the deque is the current window's maximum.",
    viewport: 'linear',
    level: 'intermediate',
    tags: ['monotonic deque', 'amortised O(1)', 'one pass', 'stream friendly'],
    aka: ['monotonic deque', 'sliding window maximum'],
  },
  {
    id: 'hash-table',
    title: 'Hash Table with Chaining',
    category: 'hashing',
    summary:
      "Hash a key to an integer, reduce it modulo the number of buckets, and link it into that bucket's chain. Double the table when more than three quarters of the slots are full.",
    viewport: 'hash',
    level: 'intermediate',
    tags: ['amortised O(1)', 'separate chaining', 'resizes', 'unordered'],
    aka: ['separate chaining', 'rehash', 'load factor'],
  },
  {
    id: 'top-k-frequent',
    title: 'Top K Frequent Elements',
    category: 'hashing',
    summary:
      'Count every value into a frequency table, then keep the k with the highest counts, breaking an equal count by whichever value appeared earliest in the input.',
    viewport: 'array',
    level: 'intermediate',
    tags: [
      'counting',
      'one pass',
      'frequency map',
      'top-k',
      'rule: count desc, first-seen asc',
      'answer is fully determined',
    ],
    aka: ['top k', 'k most frequent', 'frequency map', 'tie break', 'bucket sort'],
  },
  {
    id: 'two-sum-hash',
    title: 'Two Sum with a Hash Map',
    category: 'hashing',
    summary:
      'Walk the array once, remembering every value you have seen with its index. For each new value, one lookup answers whether its complement has already passed by.',
    viewport: 'hash',
    level: 'intro',
    tags: ['one pass', 'unsorted input', 'early exit', 'O(n) space'],
    aka: ['two sum', 'hash map'],
  },
  {
    id: 'avl-rotate',
    title: 'AVL Insert',
    category: 'trees',
    summary:
      'Insert as in a BST, then walk back up the same path recomputing subtree heights and rotating at most once to restore balance.',
    viewport: 'tree',
    level: 'advanced',
    tags: ['self-balancing', 'rotations', 'guaranteed O(log n)', 'path fix-up'],
    aka: ['avl', 'self balancing', 'rotate', 'rebalance'],
  },
  {
    id: 'bst-delete',
    title: 'BST Delete',
    category: 'trees',
    summary:
      "Find the node, then fix the parent: clear one pointer for a leaf, lift a single child, or copy in the in-order successor and delete it in the successor's place.",
    viewport: 'tree',
    level: 'advanced',
    tags: ['ordered', 'pointer surgery', 'successor', 'three cases'],
    aka: ['binary search tree', 'remove', 'successor'],
  },
  {
    id: 'bst-insert',
    title: 'BST Insert',
    category: 'trees',
    summary:
      'Walk down from the root comparing keys, and hang the new key in the first empty child slot you find.',
    viewport: 'tree',
    level: 'intro',
    tags: ['ordered', 'O(log n) average', 'O(n) worst case', 'degenerate on sorted input'],
    aka: ['binary search tree', 'insert'],
  },
  {
    id: 'bst-search',
    title: 'BST Search',
    category: 'trees',
    summary:
      'Walk down from the root, comparing at each node and discarding the subtree the target cannot be in.',
    viewport: 'tree',
    level: 'intro',
    tags: ['ordered', 'O(log n) average', 'O(n) worst case', 'pointer chasing'],
    aka: ['binary search tree', 'find'],
  },
  {
    id: 'inorder-traversal',
    title: 'In-order Traversal',
    category: 'trees',
    summary:
      'Visit the left subtree, then the node, then the right subtree — and watch the call stack push and pop as the output appears in sorted order.',
    viewport: 'tree',
    level: 'intermediate',
    tags: ['recursion', 'call stack', 'sorted output', 'O(n)'],
    aka: ['in order', 'recursion', 'sorted output'],
  },
  {
    id: 'tree-height',
    title: 'Tree Height',
    category: 'trees',
    summary:
      'Measure both subtrees before touching the node, so a height exists the moment you need it — and a balance check comes out of the same pass.',
    viewport: 'tree',
    level: 'intermediate',
    tags: ['recursion', 'post-order', 'balance check', 'O(n)'],
    aka: ['post order', 'balanced check', 'depth'],
  },
  {
    id: 'build-heap',
    title: 'Build a Min-Heap',
    category: 'heaps',
    summary:
      'Sift every internal node down once, starting from the last parent and working left. Total cost O(n), not the O(n log n) of inserting values one at a time.',
    viewport: 'tree',
    level: 'intermediate',
    tags: ['linear build', 'implicit tree', 'in place', 'Floyd heapify'],
    aka: ['heapify', 'bottom up', 'heap'],
  },
  {
    id: 'heapsort',
    title: 'Heapsort by Extraction (min-heap, descending)',
    category: 'heaps',
    summary:
      'Build a min-heap in O(n), then swap the root to the end of the active region n-1 times, shrinking the region by one and sifting the new root back down each round.',
    viewport: 'tree',
    level: 'intermediate',
    tags: ['O(1) space', 'worst-case O(n log n)', 'not stable', 'in place'],
    aka: ['heap sort', 'priority queue', 'in place'],
  },
  {
    id: 'trie',
    title: 'Trie: Insert and Prefix Search',
    category: 'tries',
    summary:
      'Store every distinct prefix as a node, one edge per character, and flag the nodes where a word ends. A prefix query is then just a walk along edges you already drew.',
    viewport: 'trie',
    level: 'intermediate',
    tags: ['prefix sharing', 'O(prefix) query', 'no false positives', 'ordered sweep'],
    aka: ['prefix tree', 'radix', 'insert', 'prefix search'],
  },
  {
    id: 'a-star-search',
    title: 'A* Search',
    category: 'graphs',
    summary:
      'Dijkstra with a guess mixed into the queue key: expand the node with the lowest g + h, where g is the cost already paid and h is a straight-line estimate of what is left, and stop the moment the goal is popped rather than merely reached.',
    viewport: 'graph',
    level: 'advanced',
    tags: ['heuristic-search', 'shortest-path', 'priority-queue', 'weighted', 'informed-search'],
    aka: ['a star', 'astar', 'a*', 'heuristic', 'informed search', 'admissible'],
  },
  {
    id: 'bellman-ford',
    title: 'Bellman-Ford',
    category: 'graphs',
    summary:
      'Sweep the whole edge list V-1 times, lowering any distance a cheaper route would beat, and use one extra sweep to prove whether the graph contains a reachable negative cycle.',
    viewport: 'graph',
    level: 'advanced',
    tags: ['shortest-path', 'negative-weights', 'negative-cycle-detection', 'single-source'],
    aka: ['shortest path', 'negative weights', 'relaxation'],
  },
  {
    id: 'bfs',
    title: 'Breadth-First Search',
    category: 'graphs',
    summary:
      'Flood the graph outwards one hop at a time from a start node, using a queue, so the first time a node is reached is by a path with the fewest edges.',
    viewport: 'graph',
    level: 'intro',
    tags: ['traversal', 'shortest-hop-path', 'queue', 'unweighted'],
    aka: ['breadth first', 'queue', 'shortest path unweighted', 'level order'],
  },
  {
    id: 'dfs',
    title: 'Depth-First Search',
    category: 'graphs',
    summary:
      'Follow one branch of the graph as far as it goes before backing up, using a stack, so the visit order traces whole subtrees rather than layers.',
    viewport: 'graph',
    level: 'intro',
    tags: ['traversal', 'stack', 'cycle-detection', 'unweighted'],
    aka: ['depth first', 'stack', 'backtracking'],
  },
  {
    id: 'dijkstra',
    title: "Dijkstra's Shortest Path",
    category: 'graphs',
    summary:
      "Repeatedly expand the discovered node with the smallest tentative distance, lowering each neighbour's best-known cost as you go, until every reachable distance is final.",
    viewport: 'graph',
    level: 'intermediate',
    tags: ['priority-queue', 'shortest-path', 'weighted', 'non-negative-weights', 'single-source'],
    aka: ['shortest path', 'priority queue', 'greedy', 'non negative'],
  },
  {
    id: 'flood-fill',
    title: 'Flood Fill',
    category: 'graphs',
    summary:
      "Claim every cell reachable from a start cell by four-way steps, using an explicit stack, so the painted set is exactly the start cell's connected component.",
    viewport: 'graph',
    level: 'intermediate',
    tags: ['grid', 'traversal', 'stack', 'reachability', 'four-way'],
    aka: ['floodfill', 'four connected', 'region fill'],
  },
  {
    id: 'kruskal',
    title: "Kruskal's Minimum Spanning Tree",
    category: 'graphs',
    summary:
      'Consider every edge from cheapest to dearest and keep it unless its endpoints are already joined, which is decided by a union-find forest rather than by searching for a path.',
    viewport: 'graph',
    level: 'advanced',
    tags: ['greedy', 'mst', 'union-find', 'undirected', 'sort-based'],
    aka: ['mst', 'minimum spanning tree', 'union find', 'disjoint set'],
  },
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    category: 'graphs',
    summary:
      'Sweep the grid, and every time the sweep meets land no flood has reached, count one island and flood the whole four-way region so it can never be counted again.',
    viewport: 'grid',
    level: 'intermediate',
    tags: ['grid', 'traversal', 'flood fill', 'counting', 'four-way', 'connected components'],
    aka: ['islands', 'connected components', 'grid dfs', 'four connected', 'eight connected'],
  },
  {
    id: 'prims-mst',
    title: "Prim's Minimum Spanning Tree",
    category: 'graphs',
    summary:
      'Grow one tree a node at a time: keep a priority queue of the edges crossing from the tree to everything outside it, take the cheapest, and drag its far end in — so an edge that would close a loop is never even a candidate.',
    viewport: 'graph',
    level: 'intermediate',
    tags: ['greedy', 'mst', 'priority-queue', 'undirected', 'grow-one-tree'],
    aka: ['prim', 'minimum spanning tree', 'mst', 'grow a tree'],
  },
  {
    id: 'topological-sort',
    title: 'Topological Sort (Kahn)',
    category: 'graphs',
    summary:
      "Repeatedly emit any node with no unemitted in-edges, decrementing its successors' in-degree counts as it goes, until every node has an output position.",
    viewport: 'graph',
    level: 'intermediate',
    tags: ['dag', 'scheduling', 'dependency-order', 'cycle-detection', 'in-degree'],
    aka: ['toposort', 'kahn', 'dag', 'in degrees'],
  },
  {
    id: 'tower-of-hanoi',
    title: 'Tower of Hanoi',
    category: 'recursion',
    summary:
      'Move a tower of n disks from one rod to another using a third, by moving the n-1 smaller disks out of the way, moving the big one, and moving the smaller ones back — which is 2^n - 1 moves.',
    viewport: 'linear',
    level: 'intermediate',
    tags: ['recursive', 'exponential work', 'linear stack depth', 'optimal move count'],
    aka: ['hanoi', 'recursion', 'call stack'],
  },
];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(
  CATALOG.map((e) => [e.id, e]),
);

export function catalogInCategory(category: Category): CatalogEntry[] {
  return CATALOG.filter((e) => e.category === category);
}

export const CATEGORY_ORDER: Category[] = CATEGORIES.map((c) => c.id);

/**
 * What the app opens on.
 *
 * Generated rather than hand-written, and derived from `CATALOG[0]` so it cannot
 * drift from what exists. It lives here rather than in `registry.ts`, and that
 * placement is load-bearing: `registry.ts` statically imports *every* algorithm
 * module, so importing anything from it — even a string constant — drags every
 * generator and all four source listings per algorithm into the initial bundle.
 * That one import took the payload from 60 kB to 371 kB gzip, and nothing about
 * it looked wrong in review.
 *
 * `catalog.ts` is pure data, so anything derived from it is free.
 */
export const DEFAULT_ALGORITHM_ID = CATALOG[0]?.id ?? 'bubble-sort';

export const CATEGORY_BLURB: Record<Category, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c.blurb]),
) as Record<Category, string>;

/**
 * Case-insensitive search across title, summary, tags and alternate names.
 *
 * Every whitespace-separated term must match somewhere, so "stable in place"
 * narrows rather than widening. Plain `includes` rather than a token index: the
 * catalog is a few dozen entries and a student types three characters, not
 * three hundred.
 */
export function searchCatalog(query: string): CatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  const terms = q.split(/\s+/);
  return CATALOG.filter((e) => {
    const haystack = [e.title, e.summary, ...e.tags, ...(e.aka ?? []), e.category]
      .join(' ')
      .toLowerCase();
    return terms.every((t) => haystack.includes(t));
  });
}
