import type { CatalogEntry } from './catalog-types.ts';
import { CATEGORIES, type Category } from './types.ts';

export type { CatalogEntry };

/**
 * The navigation index.
 *
 * Pure data: no generators, no lesson source strings, no imports of the
 * algorithm modules themselves. That is the entire point. The sidebar renders
 * from this, so opening the app costs a few kilobytes instead of dragging 50+
 * generators and 200+ code listings into the initial bundle. The selected
 * algorithm's module is then fetched with a dynamic `import()`.
 *
 * GENERATED by `npm run gen:catalog` (tools/genCatalog.ts) from the modules' own
 * metadata, because a hand-maintained duplicate of six fields per algorithm is a
 * duplicate that will drift. `contract.test.ts` asserts the two agree, so a
 * forgotten regeneration is a failing test rather than a stale sidebar.
 *
 * The one thing that is *not* generated from the modules is the search
 * vocabulary — `tags` and `aka`. Those are the words a student would actually
 * type ("divide and conquer", "nlogn", "tortoise and hare"), and no amount of
 * reading a module tells you them. They live in `EXTRA` in the generator.
 *
 * Layout of an entry: category order first (the curriculum order, not
 * alphabetical — a student should meet bubble sort before quicksort), then by
 * title within the category.
 */

export const CATALOG: CatalogEntry[] = [
  {
    id: 'bubble-sort',
    title: 'Bubble Sort',
    category: 'sorting',
    summary:
      'Repeatedly swap adjacent pairs that are out of order, until a whole pass finds nothing to fix.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(n)',
      average: 'O(n²)',
      worst: 'O(n²)',
      space: 'O(1)',
      note: 'In place, and stable — because it only swaps on a strict `>`.',
    },
    tags: ['quadratic'],
    aka: ['sinking sort', 'exchange sort'],
  },
  {
    id: 'counting-sort',
    title: 'Counting Sort',
    category: 'sorting',
    summary:
      'Tabulate how many times each value occurs in a row indexed by value, turn the tallies into running totals, and write every value into the slot its total names.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n + k)',
      average: 'O(n + k)',
      worst: 'O(n + k)',
      space: 'O(n + k)',
      note: 'k = max - min + 1, so the honest bound is O(n + k) and not O(n): every integer in the range is paid for whether or not it occurs, and doubling the range doubles both the time and the memory. Integers only — there is no counter for 3.5, and rounding one merges it with its neighbour. Space is n + k and not the k the picture suggests, because the placement has to read from a copy of the input: the writes go back into the values array, but reading them from there would hand back a value that an earlier write had already moved. The textbook version spends that same n on a second output array instead.',
    },
    tags: ['non-comparative', 'linear in n + k', 'stable', 'integers only', 'k can dominate'],
    aka: ['frequency sort', 'non comparison sort', 'prefix sums', 'linear time sort'],
  },
  {
    id: 'heap-sort',
    title: 'Heap Sort',
    category: 'sorting',
    summary:
      'Build a max-heap in the array itself, then repeatedly park the root at the far end and sift the replacement back down.',
    viewport: 'array',
    level: 'advanced',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      space: 'O(1)',
      note: 'Building the heap is O(n) because the nodes are sifted bottom-up by decreasing height; the n - 1 extractions are O(n log n) each. Not stable — the sift-down swaps distant elements — and the memory access pattern jumps around the array, so it is measurably slower than quicksort in practice.',
    },
    tags: ['divide and conquer', 'heap', 'guaranteed n log n', 'no recursion'],
    aka: ['heapsort', 'in place', 'worst case O(nlogn)'],
  },
  {
    id: 'insertion-sort',
    title: 'Insertion Sort',
    category: 'sorting',
    summary:
      'Grow a sorted prefix one element at a time, sliding every bigger value in that prefix one place to the right.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(n)',
      average: 'O(n²)',
      worst: 'O(n²)',
      space: 'O(1)',
      note: "Stable, because the walk stops on `>` rather than `>=`. In place, and the number of writes is the shift count plus one per element — a better bound than selection sort's average, but far worse than its worst case.",
    },
    tags: ['quadratic', 'online', 'adaptive'],
    aka: ['insort', 'online sort'],
  },
  {
    id: 'merge-sort',
    title: 'Merge Sort',
    category: 'sorting',
    summary:
      'Split the array in half, sort each half recursively, then interleave the two sorted runs into a shared auxiliary buffer.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      space: 'O(n)',
      note: 'Not in place, and not just because of the buffer: the recursion also costs O(log n) stack, though that vanishes next to the buffer. Stable, because the merge takes from the left half on a tie. Every input costs exactly the same, which is the property most worth having.',
    },
    tags: ['divide and conquer', 'guaranteed n log n', 'external sort'],
    aka: ['mergesort', 'divide and conquer', 'stable sort'],
  },
  {
    id: 'quick-sort',
    title: 'Quick Sort',
    category: 'sorting',
    summary:
      'Partition around a pivot so everything smaller ends up left of it, then sort the two halves independently.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n^2)',
      space: 'O(log n)',
      note: 'In place, but the *stack* is O(log n) on average and O(n) in the worst case — the last-element pivot makes that a real risk, not a formality. Not stable in the general case; the `<=` here happens to make this variant stable, but changing the comparison or the partition scheme breaks it.',
    },
    tags: ['divide and conquer', 'lomuto', 'in place', 'quadratic worst case'],
    aka: ['quicksort', 'divide and conquer', 'partition'],
  },
  {
    id: 'radix-sort',
    title: 'Radix Sort (LSD)',
    category: 'sorting',
    summary:
      'Counting sort by the units digit, then by the tens digit, then by the hundreds digit: one stable pass per place value, from the least significant digit up.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(d · (n + 10))',
      average: 'O(d · (n + 10))',
      worst: 'O(d · (n + 10))',
      space: 'O(n + 10)',
      note: 'd is the number of digits in the largest value, so the cost follows the size of the numbers rather than the number of them — 1,000 nine-digit values cost about what 1,000 single-digit ones do, and doubles are not admitted at all. Since k is pinned at 10 this never has counting sort’s blow-up, but it is not in place: a pass reads one array while writing another, which is O(n) of scratch and the same read hazard that makes the in-place counting sort wrong. Past d ≈ log₂ n the linear-per-pass advantage is spent and a comparison sort wins again.',
    },
    tags: ['non-comparative', 'LSD', 'k is always 10', 'stable passes', 'integers only'],
    aka: ['lsd', 'least significant digit', 'non comparison sort', 'stable sort by digit'],
  },
  {
    id: 'selection-sort',
    title: 'Selection Sort',
    category: 'sorting',
    summary:
      'Scan the unsorted region for its smallest value, then swap that value into the first free position.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(n²)',
      average: 'O(n²)',
      worst: 'O(n²)',
      space: 'O(1)',
      note: 'Always n²/2 comparisons — there is no early exit — but at most n - 1 writes, which is the fewest of any in-place comparison sort. Stable, because the scan only ever compares with `<`.',
    },
    tags: ['quadratic', 'minimum writes', 'exchange sort'],
    aka: ['sel sort'],
  },
  {
    id: 'shell-sort',
    title: 'Shell Sort',
    category: 'sorting',
    summary:
      'Insertion sort run repeatedly with a shrinking gap, so big values can move a long way in very few writes.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n^1.3)',
      worst: 'O(n^1.5)',
      space: 'O(1)',
      note: 'The bound is genuinely gap-sequence dependent: O(n^1.5) is the bound for the halving sequence shown and for Knuth 3x+1. The O(n²) figure in most textbooks is the bound for an arbitrary gap sequence. Stable, because every pass uses a strict `>`.',
    },
    tags: ['quadratic', 'gap sequence', 'exchange sort', 'adaptive'],
    aka: ['shellsort', 'gap sort', 'diminishing increments'],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    category: 'searching',
    summary:
      'Probe the middle of the remaining range, then discard the half that cannot hold the target.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(log n)',
      worst: 'O(log n)',
      space: 'O(1)',
      note: 'Best and worst are the same up to a constant because the halving is driven by the indices, not by the data. The real cost is the precondition: whoever sorted the array paid O(n log n), and that bill is only worth it if you search more than about log n times.',
    },
    tags: ['sorted input', 'logarithmic', 'divide and conquer'],
    aka: ['binsearch', 'halving', 'logarithmic'],
  },
  {
    id: 'exponential-search',
    title: 'Exponential Search',
    category: 'searching',
    summary:
      'Double a bound until it is past the target, then binary search only the window the doubling proved the answer lies in.',
    viewport: 'array',
    level: 'advanced',
    complexity: {
      best: 'O(1)',
      average: 'O(log i)',
      worst: 'O(log n)',
      space: 'O(1)',
      note: 'O(log i) where i is the index of the answer, not the length of the array — that is the whole difference from binary search and it only matters when the length is unknown or the answer is usually early. Worst case is still O(log n), so this is never asymptotically better, only differently shaped.',
    },
    tags: ['sorted input', 'unbounded input', 'log of the answer'],
    aka: ['doubling search', 'galloping'],
  },
  {
    id: 'jump-search',
    title: 'Jump Search',
    category: 'searching',
    summary:
      'Compare only the last cell of each √n-sized block to skip whole blocks, then linearly scan the one block that could hold the target.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(sqrt n)',
      worst: 'O(sqrt n)',
      space: 'O(1)',
      note: '√n for the jumps plus √n for the scan, so the worst case is 2√n. Strictly worse than binary search asymptotically, and its real virtue is that it makes no data-dependent branches — which is a hardware argument, not a complexity one.',
    },
    tags: ['sorted input', 'sqrt decomposition', 'branch friendly'],
    aka: ['block search', 'sqrt decomposition'],
  },
  {
    id: 'linear-search',
    title: 'Linear Search',
    category: 'searching',
    summary:
      'Walk the array from one end to the other, comparing each value with the target until they match or the array runs out.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n/2)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'O(1) needs no precondition at all, which is why the average is a flat n/2 rather than a distribution: half the array on a coin flip. A miss is always O(n) — you cannot prove absence without looking.',
    },
    tags: ['unsorted', 'no precondition', 'single lookup'],
    aka: ['sequential search', 'brute force'],
  },
  {
    id: 'lower-bound',
    title: 'Lower Bound',
    category: 'searching',
    summary:
      'Binary search that never looks for equality — it halves the window until one index is left, and that index is the first value at least the target.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(log n)',
      worst: 'O(log n)',
      space: 'O(1)',
      note: 'The cost does not depend on whether the target is present — a hit and a miss both take log n probes, which is the property binary search does not have. Space is O(1) but note this is a *distinct* function from binary search, not a flag on it: the two disagree whenever there are duplicates.',
    },
    tags: ['sorted input', 'insertion point', 'logarithmic', 'no failure case'],
    aka: ['bisect', 'first index at least', 'partition point'],
  },
  {
    id: 'search-rotated',
    title: 'Search Rotated Array',
    category: 'searching',
    summary:
      'Binary search on a sorted-then-rotated array, identifying which half of the window is still in order and discarding the other.',
    viewport: 'array',
    level: 'advanced',
    complexity: {
      best: 'O(1)',
      average: 'O(log n)',
      worst: 'O(log n)',
      space: 'O(1)',
      note: 'Identical to binary search. The rotation costs one extra comparison per probe — the a[low] <= a[mid] test — not an extra log factor, and no index, no linear pass to find the cut, and no in-place rotation. Not stable in any meaningful sense: it returns an index, and which copy of a duplicate it lands on is arbitrary.',
    },
    tags: ['sorted then rotated', 'logarithmic', 'no index needed'],
    aka: ['rotated sorted', 'unknown pivot'],
  },
  {
    id: 'container-most-water',
    title: 'Container With Most Water',
    category: 'two-pointers',
    summary:
      'Squeeze two pointers in from the ends of a list of wall heights, measure the rectangle the water would fill, and retire whichever wall is shorter — the one that can no longer be part of anything better.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'At most n - 1 pairs are ever measured against n(n-1)/2 for brute force, and the span halves every step so the work is bounded by the span rather than the count. Sortedness is not a precondition — it only makes one of the two branches unreachable, which is why the presets sort and the algorithm does not care.',
    },
    tags: ['read-only', 'greedy elimination', 'no extra space', 'works unsorted'],
    aka: ['max area', 'two pointers'],
  },
  {
    id: 'dutch-national-flag',
    title: 'Dutch National Flag',
    category: 'two-pointers',
    summary:
      'One pass, three cursors: settle a 0 at the front, a 2 at the back, and a 1 where it already stands, never letting the cursor that is inspecting advance past a value a swap has just dragged onto it.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'At most n classifications and at most n swaps, and the loop is the only thing that runs — which is what it buys over a two-pass partition at 2n. The caveat is the C++ listing, which takes its vector by value because the verification driver hands the function a temporary, so that one spelling copies O(n); the O(1) claim is about the algorithm, not about every way of writing it down.',
    },
    tags: ['one pass', 'three pointers', 'no extra space', 'not stable'],
    aka: ['sort colors', 'sort colours', 'three way partition', '3 way partition', 'one pass'],
  },
  {
    id: 'pair-sum',
    title: 'Pair Sum',
    category: 'two-pointers',
    summary:
      'Walk two pointers in from the ends of a sorted array, adding them up and throwing away whichever one could not possibly be part of a pair that hits the target.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'The cost is the number of pairs the pointers actually meet, so a hit on the first probe is O(1) and a miss is always the full n - 1 steps. The O(1) space claim only holds because it reports indices; returning the two values would be the same cost.',
    },
    tags: ['sorted input', 'no extra space', 'returns indices', 'sentinel for not-found'],
    aka: ['two sum', 'sorted two pointers'],
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    category: 'two-pointers',
    summary:
      'Walk two cursors in from the ends of a skyline and settle the column behind whichever running maximum is smaller, because that ceiling is already the tallest one the column can ever see.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'One step per column, so the cost is n rather than the n^2 bar visits of a per-column max-left/max-right scan — and unlike a sort, the best and worst cases are the same case, because the window shrinks by exactly one either way. The caveat is the initialisation: both maxima start at 0, which encodes "the ground is at zero and heights are non-negative". A negative bar would make the algorithm add water above ground level and report a total that is quietly wrong rather than an error.',
    },
    tags: ['read-only', 'no extra space', 'greedy elimination', 'works unsorted'],
    aka: ['rain water', 'water trapping', 'two pointers', 'max left max right'],
  },
  {
    id: 'valid-palindrome',
    title: 'Valid Palindrome',
    category: 'two-pointers',
    summary:
      'Walk two pointers in from the ends of a string, step over everything that is not a letter or a digit, fold away case, and stop the first time the two ends disagree.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'O(1) space because the string is never copied: each pointer only ever moves inward, so at most n/2 comparisons happen and a mismatch usually ends the walk much earlier. The honest caveat is that the four listings do not agree on what a "letter" is — JavaScript\'s regex is ASCII-only while Python, Java and C++ accept Unicode — so on non-ASCII input the answers can differ.',
    },
    tags: ['read-only', 'no extra space', 'early exit', 'case insensitive'],
    aka: ['palindrome', 'in place'],
  },
  {
    id: 'kadane',
    title: "Kadane's Algorithm",
    category: 'sliding-window',
    summary:
      'Scan left to right keeping the largest sum of any subarray that ends at the current position, throwing the running window away entirely the moment its sum turns negative.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'Linear in every case, which is unusual for a maximum-subarray problem where the brute force is O(n^2) — and it stays O(1) space only because exactly one candidate window is kept alive. The number of *distinct* subarrays that were ever "the best ending here" is n, and the overlay row is the honest picture of that; storing it costs O(n) and is the version to use when the caller wants the running values.',
    },
    tags: ['single pass', 'no extra space', 'returns a range', 'negative numbers'],
    aka: ['max subarray', 'prefix minimum'],
  },
  {
    id: 'longest-repeating-replacement',
    title: 'Longest Repeating Character Replacement',
    category: 'sliding-window',
    summary:
      'Slide a window along the string and keep the longest one that can be turned into a single repeated character within a budget of k replacements, using a most-frequent-character count that is allowed to go stale.',
    viewport: 'array',
    level: 'advanced',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(min(n, alphabet))',
      note: 'Linear, and the guarantee that makes it linear is that the record is raised at most as many times as the largest character count in the whole string — so the inner while loop runs O(n) times in total across all right values, not per right. The space is the alphabet, so the fixed 256-entry tables in the Java and C++ listings are genuinely O(1) and the Map in the JavaScript one is O(distinct characters).',
    },
    tags: [
      'single pass',
      'approximate matching',
      'stale record trick',
      'no extra copy of the input',
    ],
    aka: ['character replacement', 'sliding window'],
  },
  {
    id: 'longest-substring',
    title: 'Longest Substring Without Repeating Characters',
    category: 'sliding-window',
    summary:
      'Slide a window over the string, remembering where each character was last seen, and when a repeat turns up jump the left edge straight past the earlier copy instead of creeping forward one step at a time.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(min(n, alphabet))',
      note: 'Linear, not quadratic, and the `Math.max` on the shrink step is the reason: without it `left` can be dragged backwards. The space is the alphabet, not the input — which is why a fixed 256-entry table in C++ is a constant and a `Map` in JavaScript is O(distinct characters seen).',
    },
    tags: ['single pass', 'no extra copy of the input', 'amortised O(1) per character'],
    aka: ['longest substring without repeating', 'sliding window'],
  },
  {
    id: 'min-window-substring',
    title: 'Minimum Window Substring',
    category: 'sliding-window',
    summary:
      'Grow a window one character at a time from the right, and the moment it contains every character the pattern needs, push the left edge in as far as it will go before letting the right edge move again.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n + m)',
      average: 'O(n + m)',
      worst: 'O(n + m)',
      space: 'O(m)',
      note: 'Linear in the text plus linear in the pattern, and the reason is that each pointer moves in one direction only: `right` visits every character once and `left` visits every character once, so the nested loop is not nested in any meaningful sense. Space is the size of the pattern alphabet, not the text — which is why the Java and C++ listings can use two fixed 256-entry arrays and the JavaScript one can use a Map that grows to at most the alphabet size.',
    },
    tags: ['single pass', 'unordered pattern', 'returns a range', 'empty string for not-found'],
    aka: ['smallest window', 'sliding window'],
  },
  {
    id: 'activity-selection',
    title: 'Activity Selection',
    category: 'greedy',
    summary:
      'Take the interval that finishes earliest, then take each later interval that starts at or after the finish of the last one taken — a greedy whose exchange argument is one sentence long and needs no dynamic programming.',
    viewport: 'array',
    level: 'intro',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'O(n) *after* the sort, and the sort is not free: the algorithm as written assumes intervals arrive ordered by finish time, and this module does that sorting during input construction so the trace shows the greedy rather than the sort. With the sort included this is O(n log n), and the space is O(1) only because the sort is not being counted — an in-place sort such as heapsort would make the whole thing O(1) space.',
    },
    tags: ['read-only', 'no extra space', 'pre-sorted input', 'greedy is provably optimal'],
    aka: ['interval scheduling', 'greedy', 'earliest finish'],
  },
  {
    id: 'gas-station',
    title: 'Gas Station',
    category: 'greedy',
    summary:
      'One pass with two running sums: a tank that restarts whenever it goes negative, and a total that never does — and only the total decides whether a start exists at all.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'Linear in every case with no early exit, which is the point: the answer depends on the total over the whole loop, so there is nothing to stop early for. The space is three integers regardless of the number of stations, and the O(n^2) alternative is not merely slower but a different kind of object — it enumerates candidates, this one eliminates them.',
    },
    tags: ['read-only', 'no extra space', 'returns -1 when impossible', 'bulk elimination'],
    aka: ['gas', 'greedy', 'circular'],
  },
  {
    id: 'jump-game-2',
    title: 'Jump Game II',
    category: 'greedy',
    summary:
      'Sweep a single "farthest reachable" boundary forwards across the array, and count how many times it has to be committed before the last cell is inside it — a breadth-first search with the queue flattened into two integers.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'Linear because each index is examined once and the frontier is two integers rather than a queue; the inner-looking structure is not nested because a layer commit and an index scan are the same loop. The best case is O(1) for an array of one element, and there is no separate best case for a large array — every reachable input costs the same O(n) scan, which is unusual and worth knowing.',
    },
    tags: ['read-only', 'no extra space', 'returns -1 for unreachable', 'BFS layer greedy'],
    aka: ['jump game', 'greedy', 'fewest jumps'],
  },
  {
    id: 'knapsack',
    title: '0/1 Knapsack',
    category: 'dynamic-programming',
    summary:
      'Fill a table of "best value using the items above me and at most this capacity", taking the better of the cell above and the cell diagonally up-left.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(mC)',
      average: 'O(mC)',
      worst: 'O(mC)',
      space: 'O(mC)',
      note: 'm items, C capacity. With m = 100 items and C = 100,000 weight units that is ten million cells — which is why the practical trick is to shrink one dimension (group items by weight, or keep a 1-D table of "best value for weight at most w" processed backwards). Every cell is constant work, so there is no interesting best case.',
    },
    tags: ['table', '0/1 choice', 'capacity', 'provenance tags', 'quadratic'],
    aka: ['0/1 knapsack', 'dp', 'value per weight'],
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    category: 'dynamic-programming',
    summary:
      'Fill a table of "fewest coins to make this amount using the coins in the rows above me", reading leftwards so a coin can be reused.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(kA)',
      average: 'O(kA)',
      worst: 'O(kA)',
      space: 'O(kA)',
      note: 'k denominations, A the amount. The 1-D form (one row, updated in increasing order of amount) gives O(A) space and is the version to write by hand, since the row above is dead after it has been read once.',
    },
    tags: ['table', 'unbounded', 'sentinel', 'quadratic'],
    aka: ['minimum coins', 'dp', 'unbounded'],
  },
  {
    id: 'edit-distance',
    title: 'Edit Distance',
    category: 'dynamic-programming',
    summary:
      'Turn two strings into each other for the fewest single-character insertions, deletions and substitutions, and record which edit each cell paid for.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(mn)',
      average: 'O(mn)',
      worst: 'O(mn)',
      space: 'O(mn)',
      note: 'Every cell is three candidates and a min, so there is no interesting best case. The 1-D form — one row, updated in place, plus a byte per cell recording the direction — gets space to O(n) and still yields an edit script, which is what diff actually needs.',
    },
    tags: ['table', 'strings', 'edit script', 'symmetric'],
    aka: ['levenshtein', 'dp', 'distance'],
  },
  {
    id: 'fibonacci',
    title: 'Fibonacci',
    category: 'dynamic-programming',
    summary:
      'Compute each subproblem once by remembering the answers, then compute the same sequence again in increasing order and watch the two agree.',
    viewport: 'grid',
    level: 'intro',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'Both strategies are Θ(n) time. The naive recursion is O(φ^n) — about 1.618^n calls — because it re-derives F(k-1) for every k. The n = 20 preset is the whole argument: 21 calls with the table, 13,581 without.',
    },
    tags: ['memoisation', 'tabulation', 'top-down', 'bottom-up', 'recursion'],
    aka: ['fib', 'memoisation', 'tabulation', 'naive recursion'],
  },
  {
    id: 'lcs',
    title: 'Longest Common Subsequence',
    category: 'dynamic-programming',
    summary:
      'Build a table of how much each pair of prefixes shares, then walk it backwards to recover the shared sequence itself.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(mn)',
      average: 'O(mn)',
      worst: 'O(mn)',
      space: 'O(mn)',
      note: 'Every cell is constant work, so there is no interesting best case. The table is irreducible for reconstruction but not for the length: keeping two rows instead of the whole table drops space to O(n) and still gives the exact answer, at the cost of a second pass to recover the sequence.',
    },
    tags: ['table', 'strings', 'reconstruction', 'quadratic'],
    aka: ['longest common subsequence', 'dp', 'string'],
  },
  {
    id: 'lis',
    title: 'Longest Increasing Subsequence',
    category: 'dynamic-programming',
    summary:
      'Keep a sorted frontier of the smallest possible tail for every achievable run length, binary search where the next value belongs, and link each element to its predecessor.',
    viewport: 'array',
    level: 'advanced',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      space: 'O(n)',
      note: 'Strictly increasing is required — the comparison is `<`, not `<=`, so duplicates replace rather than extend. Relaxing the comparison to non-decreasing gives the longest non-decreasing subsequence for free, which is why that is not a separate algorithm.',
    },
    tags: ['binary search', 'reconstruction', 'frontier', 'n log n'],
    aka: ['longest increasing subsequence', 'dp', 'tails'],
  },
  {
    id: 'rod-cutting',
    title: 'Rod Cutting',
    category: 'dynamic-programming',
    summary:
      'Split a rod into priced pieces for the maximum revenue, tracking for every rod length and every piece budget the best revenue found so far.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(L²)',
      average: 'O(L²)',
      worst: 'O(L²)',
      space: 'O(L²)',
      note: 'L is the rod length, not the number of pieces. The 1-D form — one entry per rod length, filled in increasing order — is the same recurrence in O(L) space, and for L in the thousands that is the only version that fits in cache.',
    },
    tags: ['table', 'unbounded', 'optimisation', 'quadratic'],
    aka: ['rod cut', 'dp', 'unbounded'],
  },
  {
    id: 'detect-cycle',
    title: 'Detect a Cycle (Floyd)',
    category: 'linked-lists',
    summary:
      'Walk two cursors at different speeds. If the fast one falls off the end there is no cycle; if they meet, they must be on a ring.',
    viewport: 'linked',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'Worst case is μ + λ node visits, where μ is the tail length and λ the ring length — a million-node tail feeding a 2-node ring still terminates in time proportional to the tail. Best case O(1) is the empty or single-node list. The list is never modified and never copied.',
    },
    tags: ['two pointers', 'O(1) space', 'read-only safe', 'no allocation'],
    aka: ['floyd', 'tortoise and hare', 'linked list cycle'],
  },
  {
    id: 'merge-two-sorted',
    title: 'Merge Two Sorted Lists',
    category: 'linked-lists',
    summary:
      'Repeatedly take the smaller of the two heads and link it on. Because both inputs are already sorted, that head is always the smallest value left anywhere.',
    viewport: 'linked',
    level: 'intro',
    complexity: {
      best: 'O(n + m)',
      average: 'O(n + m)',
      worst: 'O(n + m)',
      space: 'O(min(n, m))',
      note: 'Linear in the total and the bound is tight: every node is visited exactly once, including the spliced tail. Space is O(min(n, m)) *new* nodes, not O(n + m), because the interleaved prefix is allocated and the rest of one input is reused. Stable, because `<=` hands ties to the first list.',
    },
    tags: ['linear', 'two pointers', 'sorted input', 'allocates only the prefix'],
    aka: ['merge lists', 'linked list'],
  },
  {
    id: 'reverse-list',
    title: 'Reverse a Linked List',
    category: 'linked-lists',
    summary:
      'Walk the list with two cursors and repoint every `next` field backwards, so the nodes never move and nothing is copied.',
    viewport: 'linked',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'No node is allocated, moved or copied, so the space cost is three pointers regardless of length. Best case O(1) is the empty or single-node list, where the loop body never runs at all.',
    },
    tags: ['pointer surgery', 'no allocation', 'iterative', 'O(1) space'],
    aka: ['linked list reversal', 'pointer rewiring'],
  },
  {
    id: 'balanced-brackets',
    title: 'Balanced Brackets',
    category: 'stacks-queues',
    summary:
      'Push every opener, and require each closer to match the top of the stack exactly. Balanced means the stack ends empty.',
    viewport: 'linear',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'O(n) time, with an early exit on the first mismatch so a bad string is often rejected in a few characters. Space is O(d), the maximum nesting depth, not O(n) — the "Left open" preset shows the difference between 3 nodes and a 500-character string of brackets. Best case O(1) is the empty string.',
    },
    tags: ['O(1) per character', 'nesting', 'early exit', 'stack depth is the space cost'],
    aka: ['valid parentheses', 'stack'],
  },
  {
    id: 'valid-postfix',
    title: 'Evaluate a Postfix Expression',
    category: 'stacks-queues',
    summary:
      'Read the expression left to right: a number goes on the stack, an operator takes the top two and puts their result back. One value left at the end means it was well formed.',
    viewport: 'linear',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'O(n) in the token count, with one push or one collapse per token and no rescanning. Space is O(n) in the worst case — a right-nested expression such as "1 2 3 4 + + +" pushes every operand before any operator — and O(√n) for a balanced expression, which is the reason the space cost is worth thinking about rather than assuming.',
    },
    tags: ['no parentheses', 'single pass', 'validated', 'stack machine'],
    aka: ['postfix', 'rpn', 'stack'],
  },
  {
    id: 'largest-rectangle',
    title: 'Largest Rectangle in a Histogram',
    category: 'stacks-queues',
    summary:
      'Keep a non-decreasing stack of candidate heights. A shorter bar closes off the stack top, whose widest rectangle runs from just after the new stack top to the bar before the current one — and a zero-height sentinel at the end closes off everything that is left.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'Amortised O(n) because every bar is pushed exactly once and popped at most once, so a single arriving bar cannot cost more than the pops it causes and those total at most n. The space is O(n) for the stack in the worst case — a strictly *decreasing* histogram never pops until the sentinel and holds every index — and O(1) on a strictly increasing one, where it never holds more than one bar and the whole run of measurements happens in the sentinel burst. The `online` flag needs the same caveat the next-greater stack does: the final burst is an end-of-input event, so an endless stream would need that flush exposed as a separate call.',
    },
    tags: ['monotonic stack', 'one pass', 'amortised O(1)', 'sentinel bar', 'histogram'],
    aka: ['largest rectangle in histogram', 'histogram', 'maximal rectangle', 'monotonic stack'],
  },
  {
    id: 'min-stack',
    title: 'Min Stack',
    category: 'stacks-queues',
    summary:
      'Keep a second stack of running minima, one entry per depth, so that after any pop the smallest remaining value is the top of that stack.',
    viewport: 'linear',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(1)',
      worst: 'O(1)',
      space: 'O(n)',
      note: 'Push, pop and getMin are all O(1) amortised, and getMin is O(1) *worst* case — that is the entire point. The price is a second array the same length as the data: O(n) extra memory to make one query free. The "first value is the minimum" preset is the pathological case, n extra slots to store one repeated number.',
    },
    tags: ['O(1) getMin', 'two stacks', 'pushdown automaton', 'space for speed'],
    aka: ['stack with min', 'auxiliary stack'],
  },
  {
    id: 'next-greater-element',
    title: 'Next Greater Element',
    category: 'stacks-queues',
    summary:
      'Walk left to right with a stack of unanswered indices in non-increasing order; every value that beats the top of the stack answers it, and whatever is left at the end has no greater element.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'Amortised O(n) because every index is pushed exactly once and popped at most once, so the total number of pops cannot exceed n even though a single arriving value can pop the entire stack in one step. The answer array is O(n) whatever the data does; the stack alone is O(1) on strictly ascending input and O(n) on strictly descending input, where all n indices are still waiting when the scan ends and none of them is ever answered. The `online` flag is also worth qualifying: an answer is final the moment it is written, but the -1s can only be named at end of input, so a genuinely endless stream needs a flush you call yourself.',
    },
    tags: ['monotonic stack', 'one pass', 'amortised O(1)', 'suffix query', 'sentinel -1'],
    aka: ['next greater', 'next larger element', 'monotonic stack', 'stack'],
  },
  {
    id: 'sliding-window-max',
    title: 'Sliding Window Maximum',
    category: 'stacks-queues',
    summary:
      "Keep a decreasing deque of candidate maxima. A new value throws away every smaller value behind it, and the front of the deque is the current window's maximum.",
    viewport: 'linear',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(k)',
      note: 'O(n) amortised and O(n) worst case: every value is pushed once and popped at most once, so the pops cannot outnumber the pushes even though a single push can pop the whole deque. Space is O(k), bounded by the window size — and by nothing else, which is what the "ascending input" preset makes obvious: the deque never holds more than one entry.',
    },
    tags: ['monotonic deque', 'amortised O(1)', 'one pass', 'stream friendly'],
    aka: ['monotonic deque', 'sliding window maximum'],
  },
  {
    id: 'hash-table',
    title: 'Hash Table with Chaining',
    category: 'hashing',
    summary:
      "Hash a key to an integer, reduce it modulo the number of buckets, and link it into that bucket's chain. Double the table when more than three quarters of the slots are full.",
    viewport: 'hash',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(1 + load factor)',
      worst: 'O(n)',
      space: 'O(n + capacity)',
      note: 'Average O(1) *because* the load factor is kept below 0.75, so a chain walk is bounded by a constant. Worst case is O(n) and it is not merely theoretical: an adversary who knows your hash can feed you n keys into one bucket. Space is O(n) keys plus the bucket array, so roughly 2n slots at the standard load factor.',
    },
    tags: ['amortised O(1)', 'separate chaining', 'resizes', 'unordered'],
    aka: ['separate chaining', 'rehash', 'load factor'],
  },
  {
    id: 'top-k-frequent',
    title: 'Top K Frequent Elements',
    category: 'hashing',
    summary:
      'Count every value into a frequency table, then keep the k with the highest counts, breaking an equal count by whichever value appeared earliest in the input.',
    viewport: 'array',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n + d·log d)',
      worst: 'O(n + d·log d)',
      space: 'O(d)',
      note: 'd is the number of distinct values. The counting pass is O(n) on a good hash, and the selection pass is O(d log d) in these listings because each insertion re-sorts the answer — O(d log k) with a real heap, which matters when k is 1 and d is millions. The caveat nobody mentions is the tie-break: on equal counts the answer is *not* determined by the data, so the rule — higher count first, and on a tie the value seen earliest in the input — is a decision this implementation has to make out loud. It is stated identically in all four listings, because that is what makes the four agree rather than each returning a valid answer of its own.',
    },
    tags: [
      'counting',
      'one pass',
      'frequency map',
      'top-k',
      'rule: count desc, first-seen asc',
      'answer is fully determined',
    ],
    aka: ['top k', 'k most frequent', 'frequency map', 'tie break', 'bucket sort'],
  },
  {
    id: 'two-sum-hash',
    title: 'Two Sum with a Hash Map',
    category: 'hashing',
    summary:
      'Walk the array once, remembering every value you have seen with its index. For each new value, one lookup answers whether its complement has already passed by.',
    viewport: 'hash',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'O(n) average, with a best case of O(1) when the first two values already pair up, and an O(n) worst case on a map with terrible hash distribution. Space is O(n) — a whole map — which is the entire difference from the two-pointers version, and the reason neither is universally better. Values are keys, so a hash of an int is cheap; hashing strings would dominate.',
    },
    tags: ['one pass', 'unsorted input', 'early exit', 'O(n) space'],
    aka: ['two sum', 'hash map'],
  },
  {
    id: 'avl-rotate',
    title: 'AVL Insert',
    category: 'trees',
    summary:
      'Insert as in a BST, then walk back up the same path recomputing subtree heights and rotating at most once to restore balance.',
    viewport: 'tree',
    level: 'advanced',
    complexity: {
      best: 'O(log n)',
      average: 'O(log n)',
      worst: 'O(log n)',
      space: 'O(n)',
      note: 'Insert is a descent plus a fix-up along the same path, so O(log n) with a guaranteed worst case, and at most two rotations per insert. The height is bounded by about 1.44·log2(n+2), so a million nodes are at most 21 levels deep. Lookup and delete are the same descent, which is the point: the balance makes *all* of them fast.',
    },
    tags: ['self-balancing', 'rotations', 'guaranteed O(log n)', 'path fix-up'],
    aka: ['avl', 'self balancing', 'rotate', 'rebalance'],
  },
  {
    id: 'bst-delete',
    title: 'BST Delete',
    category: 'trees',
    summary:
      "Find the node, then fix the parent: clear one pointer for a leaf, lift a single child, or copy in the in-order successor and delete it in the successor's place.",
    viewport: 'tree',
    level: 'advanced',
    complexity: {
      best: 'O(log n)',
      average: 'O(log n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'Two walks and a constant number of pointer writes, both walks O(height). In this index representation nodes are never freed, so repeated insert/delete cycles grow the arrays monotonically — a cost of the representation, not of the algorithm.',
    },
    tags: ['ordered', 'pointer surgery', 'successor', 'three cases'],
    aka: ['binary search tree', 'remove', 'successor'],
  },
  {
    id: 'bst-insert',
    title: 'BST Insert',
    category: 'trees',
    summary:
      'Walk down from the root comparing keys, and hang the new key in the first empty child slot you find.',
    viewport: 'tree',
    level: 'intro',
    complexity: {
      best: 'O(log n)',
      average: 'O(log n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'One insert is O(height): log n for a balanced tree, n for a degenerate one. The whole build is the sum of those, so sorted input is n(n-1)/2 comparisons. Nothing in the insertion code knows the difference — the worst case is entirely a property of arrival order.',
    },
    tags: ['ordered', 'O(log n) average', 'O(n) worst case', 'degenerate on sorted input'],
    aka: ['binary search tree', 'insert'],
  },
  {
    id: 'bst-search',
    title: 'BST Search',
    category: 'trees',
    summary:
      'Walk down from the root, comparing at each node and discarding the subtree the target cannot be in.',
    viewport: 'tree',
    level: 'intro',
    complexity: {
      best: 'O(1)',
      average: 'O(log n)',
      worst: 'O(n)',
      space: 'O(n)',
      note: 'Best case is a lucky probe at the root. The worst case is the degenerate tree, where search degrades to a linear scan — the same tree BST Insert builds from sorted input, which is why that preset is the one to look at first.',
    },
    tags: ['ordered', 'O(log n) average', 'O(n) worst case', 'pointer chasing'],
    aka: ['binary search tree', 'find'],
  },
  {
    id: 'inorder-traversal',
    title: 'In-order Traversal',
    category: 'trees',
    summary:
      'Visit the left subtree, then the node, then the right subtree — and watch the call stack push and pop as the output appears in sorted order.',
    viewport: 'tree',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(h)',
      note: 'Every node is visited once, so the time is always O(n). The space is the stack depth, i.e. the tree height: O(log n) balanced, O(n) degenerate — and the recursive form turns that into a real risk, since Python raises RecursionError around a thousand frames and C++ segfaults when the machine stack runs out.',
    },
    tags: ['recursion', 'call stack', 'sorted output', 'O(n)'],
    aka: ['in order', 'recursion', 'sorted output'],
  },
  {
    id: 'tree-height',
    title: 'Tree Height',
    category: 'trees',
    summary:
      'Measure both subtrees before touching the node, so a height exists the moment you need it — and a balance check comes out of the same pass.',
    viewport: 'tree',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(h)',
      note: 'Every node is visited once, so the time is always O(n) and there is no interesting best case. The stack is the height — and that is the number worth watching, because a tree whose height is n is a list, however well it is labelled.',
    },
    tags: ['recursion', 'post-order', 'balance check', 'O(n)'],
    aka: ['post order', 'balanced check', 'depth'],
  },
  {
    id: 'build-heap',
    title: 'Build a Min-Heap',
    category: 'heaps',
    summary:
      'Sift every internal node down once, starting from the last parent and working left. Total cost O(n), not the O(n log n) of inserting values one at a time.',
    viewport: 'tree',
    level: 'intermediate',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n)',
      space: 'O(1)',
      note: 'O(n) for every input, with no best case to speak of — the "already a heap" preset is O(n) too, it just does no swaps. The bound comes from summing the sifts: most nodes are near the leaves and sift furthest, but there are exponentially more of them, so the series converges to a constant times n. Space is O(1) beyond the array, because the array *is* the structure.',
    },
    tags: ['linear build', 'implicit tree', 'in place', 'Floyd heapify'],
    aka: ['heapify', 'bottom up', 'heap'],
  },
  {
    id: 'heapsort',
    title: 'Heapsort by Extraction (min-heap, descending)',
    category: 'heaps',
    summary:
      'Build a min-heap in O(n), then swap the root to the end of the active region n-1 times, shrinking the region by one and sifting the new root back down each round.',
    viewport: 'tree',
    level: 'intermediate',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      space: 'O(1)',
      note: 'O(n) to build plus n-1 extractions at O(log n) each, so O(n log n) for *every* input — there is no best case, unlike quicksort. Space is O(1) auxiliary, which is the rarest property a comparison sort has, and it is the whole reason this algorithm exists alongside its faster cousins.',
    },
    tags: ['O(1) space', 'worst-case O(n log n)', 'not stable', 'in place'],
    aka: ['heap sort', 'priority queue', 'in place'],
  },
  {
    id: 'trie',
    title: 'Trie: Insert and Prefix Search',
    category: 'tries',
    summary:
      'Store every distinct prefix as a node, one edge per character, and flag the nodes where a word ends. A prefix query is then just a walk along edges you already drew.',
    viewport: 'trie',
    level: 'intermediate',
    complexity: {
      best: 'O(1)',
      average: 'O(L)',
      worst: 'O(L)',
      space: 'O(total characters)',
      note: 'O(L) per query for a prefix of length L, *independent of the number of words stored* — that independence is the entire reason to use a trie. Insert is O(L) per word, and the total space is the number of distinct prefixes, which is at most the total characters and in practice far less. The empty-prefix query is O(1) to match and O(n) to enumerate, which is the one case where the "independent of size" claim needs a footnote.',
    },
    tags: ['prefix sharing', 'O(prefix) query', 'no false positives', 'ordered sweep'],
    aka: ['prefix tree', 'radix', 'insert', 'prefix search'],
  },
  {
    id: 'a-star-search',
    title: 'A* Search',
    category: 'graphs',
    summary:
      'Dijkstra with a guess mixed into the queue key: expand the node with the lowest g + h, where g is the cost already paid and h is a straight-line estimate of what is left, and stop the moment the goal is popped rather than merely reached.',
    viewport: 'graph',
    level: 'advanced',
    complexity: {
      best: 'O((V + E) log V)',
      average: 'O((V + E) log V)',
      worst: 'O((V + E) log V)',
      space: 'O(V + E)',
      note: "Identical to Dijkstra, and that is the ceiling rather than the bill: the bound is reached exactly when h says nothing, which is what the `no-geometry` preset is for. With a perfect h over this module's own weight scheme the search is admissible and consistent, and the node count can drop by an order of magnitude — `corridor` expands 4 of 16. The caveat that matters is not the asymptotics but the precondition: the heuristic must be admissible, and an inadmissible one does not merely slow the search down, it silently returns a wrong cost.",
    },
    tags: ['heuristic-search', 'shortest-path', 'priority-queue', 'weighted', 'informed-search'],
    aka: ['a star', 'astar', 'a*', 'heuristic', 'informed search', 'admissible'],
  },
  {
    id: 'bellman-ford',
    title: 'Bellman-Ford',
    category: 'graphs',
    summary:
      'Sweep the whole edge list V-1 times, lowering any distance a cheaper route would beat, and use one extra sweep to prove whether the graph contains a reachable negative cycle.',
    viewport: 'graph',
    level: 'advanced',
    complexity: {
      best: 'O(V · E)',
      average: 'O(V · E)',
      worst: 'O(V · E)',
      space: 'O(V)',
      note: 'Time is V-1 sweeps of the whole edge list; space is the distance table alone, because the edges live in the adjacency the caller already holds. The early exit makes the common case far cheaper — often two passes — but it is not something you can rely on.',
    },
    tags: ['shortest-path', 'negative-weights', 'negative-cycle-detection', 'single-source'],
    aka: ['shortest path', 'negative weights', 'relaxation'],
  },
  {
    id: 'bfs',
    title: 'Breadth-First Search',
    category: 'graphs',
    summary:
      'Flood the graph outwards one hop at a time from a start node, using a queue, so the first time a node is reached is by a path with the fewest edges.',
    viewport: 'graph',
    level: 'intro',
    complexity: {
      best: 'O(V + E)',
      average: 'O(V + E)',
      worst: 'O(V + E)',
      space: 'O(V)',
      note: 'Every node is enqueued once and every edge is read once, so the cost is the size of the graph — there is no worst case to fear and no input on which it degrades.',
    },
    tags: ['traversal', 'shortest-hop-path', 'queue', 'unweighted'],
    aka: ['breadth first', 'queue', 'shortest path unweighted', 'level order'],
  },
  {
    id: 'dfs',
    title: 'Depth-First Search',
    category: 'graphs',
    summary:
      'Follow one branch of the graph as far as it goes before backing up, using a stack, so the visit order traces whole subtrees rather than layers.',
    viewport: 'graph',
    level: 'intro',
    complexity: {
      best: 'O(V + E)',
      average: 'O(V + E)',
      worst: 'O(V + E)',
      space: 'O(V)',
      note: 'Same bound as BFS, and it holds on every input: each node is pushed once, each edge is read once. The stack can be as deep as the graph is long, which is the only practical difference — the recursive version stores the same thing in the machine stack instead.',
    },
    tags: ['traversal', 'stack', 'cycle-detection', 'unweighted'],
    aka: ['depth first', 'stack', 'backtracking'],
  },
  {
    id: 'dijkstra',
    title: "Dijkstra's Shortest Path",
    category: 'graphs',
    summary:
      "Repeatedly expand the discovered node with the smallest tentative distance, lowering each neighbour's best-known cost as you go, until every reachable distance is final.",
    viewport: 'graph',
    level: 'intermediate',
    complexity: {
      best: 'O((V + E) log V)',
      average: 'O((V + E) log V)',
      worst: 'O((V + E) log V)',
      space: 'O(V + E)',
      note: 'With a lazy binary heap the queue can hold O(E) entries rather than O(V), so a graph with many parallel edges is really O(E log E) — use a decrease-key heap when that matters. There is no worse case: unlike BFS and DFS, the bound holds for every input.',
    },
    tags: ['priority-queue', 'shortest-path', 'weighted', 'non-negative-weights', 'single-source'],
    aka: ['shortest path', 'priority queue', 'greedy', 'non negative'],
  },
  {
    id: 'flood-fill',
    title: 'Flood Fill',
    category: 'graphs',
    summary:
      "Claim every cell reachable from a start cell by four-way steps, using an explicit stack, so the painted set is exactly the start cell's connected component.",
    viewport: 'graph',
    level: 'intermediate',
    complexity: {
      best: 'O(R · C)',
      average: 'O(R · C)',
      worst: 'O(R · C)',
      space: 'O(R · C)',
      note: 'A four-way fill on an R×C grid touches every open cell once and reads at most four edges per cell, so it is linear in the grid and there is no input that makes it worse. Space is the claimed set plus the stack, and the stack is bounded by 3 per painted cell — not by the grid size, which is what makes the iterative version safe where the recursive one is not.',
    },
    tags: ['grid', 'traversal', 'stack', 'reachability', 'four-way'],
    aka: ['floodfill', 'four connected', 'region fill'],
  },
  {
    id: 'kruskal',
    title: "Kruskal's Minimum Spanning Tree",
    category: 'graphs',
    summary:
      'Consider every edge from cheapest to dearest and keep it unless its endpoints are already joined, which is decided by a union-find forest rather than by searching for a path.',
    viewport: 'graph',
    level: 'advanced',
    complexity: {
      best: 'O(E log E)',
      average: 'O(E log E)',
      worst: 'O(E log E)',
      space: 'O(V)',
      note: 'The sort dominates; union-find with union by size and path compression is effectively constant, at O(α(V)) amortised, where α is the inverse Ackermann function and is below 5 for any V a computer can name. Space is the parent and size arrays, not the edge list, which the caller already holds.',
    },
    tags: ['greedy', 'mst', 'union-find', 'undirected', 'sort-based'],
    aka: ['mst', 'minimum spanning tree', 'union find', 'disjoint set'],
  },
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    category: 'graphs',
    summary:
      'Sweep the grid, and every time the sweep meets land no flood has reached, count one island and flood the whole four-way region so it can never be counted again.',
    viewport: 'grid',
    level: 'intermediate',
    complexity: {
      best: 'O(R · C)',
      average: 'O(R · C)',
      worst: 'O(R · C)',
      space: 'O(R · C)',
      note: "Every cell is examined once by the scan and claimed at most once by a flood, and each claim looks at exactly four neighbours, so there is no input that makes this slower — 4-connected versus 8-connected is a constant factor, not a complexity. The one caveat is the stack: it is bounded by the island, not by the grid, so a recursive version recurses to the island's diameter and overflows the machine stack on one large open region while the iterative version is unaffected.",
    },
    tags: ['grid', 'traversal', 'flood fill', 'counting', 'four-way', 'connected components'],
    aka: ['islands', 'connected components', 'grid dfs', 'four connected', 'eight connected'],
  },
  {
    id: 'prims-mst',
    title: "Prim's Minimum Spanning Tree",
    category: 'graphs',
    summary:
      'Grow one tree a node at a time: keep a priority queue of the edges crossing from the tree to everything outside it, take the cheapest, and drag its far end in — so an edge that would close a loop is never even a candidate.',
    viewport: 'graph',
    level: 'intermediate',
    complexity: {
      best: 'O((V + E) log V)',
      average: 'O((V + E) log V)',
      worst: 'O((V + E) log V)',
      space: 'O(V + E)',
      note: "The binary heap is lazy, so it can hold O(E) entries rather than O(V) and the real bound is O(E log E) on a graph with many parallel edges; an indexed heap with a decreaseKey would be O(V) space and no stale pops. Time is one scan of each node's edges on the way in plus one pop per queue entry, and the edge scans total O(E) because every node is scanned exactly once. Space here is the inTree flags and the queue — the tree itself is not stored.",
    },
    tags: ['greedy', 'mst', 'priority-queue', 'undirected', 'grow-one-tree'],
    aka: ['prim', 'minimum spanning tree', 'mst', 'grow a tree'],
  },
  {
    id: 'topological-sort',
    title: 'Topological Sort (Kahn)',
    category: 'graphs',
    summary:
      "Repeatedly emit any node with no unemitted in-edges, decrementing its successors' in-degree counts as it goes, until every node has an output position.",
    viewport: 'graph',
    level: 'intermediate',
    complexity: {
      best: 'O(V + E)',
      average: 'O(V + E)',
      worst: 'O(V + E)',
      space: 'O(V + E)',
      note: 'The extra space over a plain BFS is the transposed edge list, not the frontier: the frontier itself never exceeds V entries. Deterministic given a fixed tie-break, which is unusual for a graph algorithm and is what makes it testable.',
    },
    tags: ['dag', 'scheduling', 'dependency-order', 'cycle-detection', 'in-degree'],
    aka: ['toposort', 'kahn', 'dag', 'in degrees'],
  },
  {
    id: 'tower-of-hanoi',
    title: 'Tower of Hanoi',
    category: 'recursion',
    summary:
      'Move a tower of n disks from one rod to another using a third, by moving the n-1 smaller disks out of the way, moving the big one, and moving the smaller ones back — which is 2^n - 1 moves.',
    viewport: 'linear',
    level: 'intermediate',
    complexity: {
      best: 'O(2^n)',
      average: 'O(2^n)',
      worst: 'O(2^n)',
      space: 'O(n)',
      note: 'Exponential in the number of disks, and the number is not a lower bound of cleverness — it is forced. Moving the largest disk needs the n-1 smaller ones on the spare rod, which needs the largest among *those* moved, and so on, so 2^n - 1 is optimal. The space is O(n) because the call stack never holds more than n frames, which is the pleasant surprise: the work is exponential and the memory is linear.',
    },
    tags: ['recursive', 'exponential work', 'linear stack depth', 'optimal move count'],
    aka: ['hanoi', 'recursion', 'call stack'],
  },
];

export const CATALOG_BY_ID: Record<string, CatalogEntry> = Object.fromEntries(
  CATALOG.map((e) => [e.id, e]),
);

export function catalogInCategory(category: Category): CatalogEntry[] {
  return CATALOG.filter((e) => e.category === category);
}

export const CATEGORY_ORDER: Category[] = CATEGORIES.map((c) => c.id);

/**
 * What the app opens on.
 *
 * Generated rather than hand-written, and derived from `CATALOG[0]` so it cannot
 * drift from what exists. It lives here rather than in `registry.ts`, and that
 * placement is load-bearing: `registry.ts` statically imports *every* algorithm
 * module, so importing anything from it — even a string constant — drags every
 * generator and all four source listings per algorithm into the initial bundle.
 * That one import took the payload from 60 kB to 371 kB gzip, and nothing about
 * it looked wrong in review.
 *
 * `catalog.ts` is pure data, so anything derived from it is free.
 */
export const DEFAULT_ALGORITHM_ID = CATALOG[0]?.id ?? 'bubble-sort';

export const CATEGORY_BLURB: Record<Category, string> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c.blurb]),
) as Record<Category, string>;

/**
 * Case-insensitive search across title, summary, tags and alternate names.
 *
 * Every whitespace-separated term must match somewhere, so "stable in place"
 * narrows rather than widening. Plain `includes` rather than a token index: the
 * catalog is a few dozen entries and a student types three characters, not
 * three hundred.
 */
export function searchCatalog(query: string): CatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  const terms = q.split(/\s+/);
  return CATALOG.filter((e) => {
    // The complexity numbers are in the haystack so that searching a cost finds
    // the algorithms that have it — "nlogn" and "linear" are things people
    // search for, and they were only reachable through a handful of hand-written
    // `aka` entries until now.
    const haystack = [
      e.title,
      e.summary,
      e.complexity.best,
      e.complexity.average,
      e.complexity.worst,
      e.complexity.space,
      ...e.tags,
      ...(e.aka ?? []),
      e.category,
    ]
      .filter(Boolean)
      .join(' ')
      .toLowerCase();
    return terms.every((t) => haystack.includes(t));
  });
}
