import type { Topic } from '../types.ts';

/**
 * Phase 2 — Core patterns.
 *
 * ## The five techniques, in the order they are taught
 *
 * Two pointers, sliding window, binary search, divide and conquer, recursion. Each
 * one answers a shape of question rather than a type of input, which is why the
 * topics are grouped the way they are: "an unsorted array" tells you nothing, but
 * "a sorted array and a target" suggests binary search before you read the problem.
 *
 * ## Two pointers and sliding window are taught apart on purpose
 *
 * They are adjacent in every list of patterns and beginners always merge them. They
 * differ in one load-bearing way: a **sliding window changes its size**, and the
 * whole difficulty is knowing *when* it is legal to shrink. A fixed two-pointer
 * walk moves both ends monotonically and never has to be retracted.
 *
 * That difference is why the sliding-window topic leads with "the window is legal to
 * shrink *because of this one condition*". If a learner can say why a shrink is
 * legal, they have the pattern. If they only know the template, they will get it
 * wrong on every problem where the window is not monotonic.
 */
export const PATTERNS: readonly Topic[] = [
  {
    id: 'two-pointers',
    title: 'Two pointers',
    blurb:
      'Two indices walking the same array, and a comparison that decides which one moves. It only works when moving a pointer cannot lose an answer — that is the entire condition, and checking it is the whole skill.',
    phase: 'patterns',
    algoIds: ['pair-sum', 'valid-palindrome', 'container-most-water'],
    learnSlugs: ['two-pointers', 'pointer-problems'],
    keyPoints: [
      'Start one pointer at each end, and let the comparison tell you which end is safe to abandon. That is the loop.',
      'Only valid on a structure where each end is independently final — usually a sorted array or a palindrome check.',
      'For 3Sum and 4Sum, fix the outer index and run two pointers inside it. That turns O(n³) into O(n²).',
      'If you ever move a pointer *backwards*, stop: you want a frequency map, not two pointers.',
    ],
    questions: [
      {
        id: 'ib-two-sum',
        title: 'Two Sum',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/two-sum/',
      },
      {
        id: 'ib-valid-triangle-from-streaks',
        title: 'Valid Triangle From Streaks',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/valid-triangle-from-streaks/',
      },
      {
        id: 'lc-valid-palindrome',
        title: 'Valid Palindrome',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/valid-palindrome/',
      },
      {
        id: 'lc-two-sum-ii',
        title: 'Two Sum II — Input Array Is Sorted',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
      },
      {
        id: 'lc-container-with-most-water',
        title: 'Container With Most Water',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/container-with-most-water/',
      },
      {
        id: 'gfg-container-with-most-water',
        title: 'Container With Most Water',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/container-with-most-water/1',
      },
      {
        id: 'gfg-three-sum-closest',
        title: 'Closest Three Sum',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/three-sum-closest/1',
      },
      {
        id: 'lc-four-sum',
        title: '4Sum',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/4sum/',
      },
      {
        id: 'ib-3-sum',
        title: 'Three Sum',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/3-rev/',
      },
      {
        id: 'lc-longest-palindromic-substring',
        title: 'Longest Palindromic Substring',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/longest-palindromic-substring/',
      },
    ],
  },

  {
    id: 'sliding-window',
    title: 'Sliding window',
    blurb:
      'A window of consecutive elements that you move one step at a time, carrying just enough state to decide whether it is valid. The hard part is never the movement — it is knowing when you are allowed to shrink.',
    phase: 'patterns',
    algoIds: ['longest-substring', 'min-window-substring', 'longest-repeating-replacement'],
    learnSlugs: ['two-pointers'],
    keyPoints: [
      'Fixed-size window: sum, min, or max of the last k elements. Two deques or two pointers, never a rescan.',
      'Variable-size window: the right end always extends, and the left end shrinks **only while the window stays valid**.',
      'If the answer is "does some substring satisfy P", the window usually needs to carry frequencies, not just a sum.',
      'If shrinking is not monotone — the condition can become true again — you need a different tool. That is where hashing or DP wins.',
    ],
    questions: [
      {
        id: 'ib-longest-substring-without-repeating',
        title: 'Longest Substring Without Repeating Characters',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/longest-substring-without-repeating-characters/',
      },
      {
        id: 'lc-longest-substring-without-repeating',
        title: 'Longest Substring Without Repeating Characters',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
      },
      {
        id: 'lc-minimum-window-substring',
        title: 'Minimum Window Substring',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/minimum-window-substring/',
      },
      {
        id: 'ib-smallest-window-substring',
        title: 'Smallest Window Substring',
        platform: 'interviewbit',
        level: 'hard',
        url: 'https://www.interviewbit.com/problems/smallest-window-substring/',
      },
      {
        id: 'ib-subarray-with-given-sum',
        title: 'Subarray with given Sum',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/subarray-with-given-sum/',
      },
      {
        id: 'gfg-subarray-with-given-sum',
        title: 'Indexes of Subarray Sum',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/subarray-with-given-sum/1',
      },
      {
        id: 'he-good-subarray',
        title: 'Good Subarray',
        platform: 'hackerearth',
        level: 'medium',
        url: 'https://www.hackerearth.com/problem/algorithm/good-subarray/',
      },
      {
        id: 'hr-longest-increasing-subsequence-arrays',
        title: 'Longest Increasing Subsequence Arrays',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/longest-increasing-subsequence-arrays/problem',
      },
    ],
  },

  {
    id: 'binary-search',
    title: 'Binary search',
    blurb:
      'Halve the search space every step. Almost every hard binary-search problem is really a question about *finding the boundary*, and almost every wrong answer comes from an off-by-one on that boundary.',
    phase: 'patterns',
    algoIds: ['binary-search', 'lower-bound', 'search-rotated', 'exponential-search'],
    learnSlugs: ['binary-search'],
    keyPoints: [
      'Invariant first. Write one sentence: "the answer, if it exists, is inside [lo, hi]" — then make every branch preserve it.',
      'Two exit styles: exact-match (`while lo <= hi`, return or -1) and boundary (`while lo < hi`, no exact match). Pick one per problem and do not mix them.',
      'The answer is usually `lo` on exit. Almost every "off by one" is really "I returned `hi` where the invariant said `lo`".',
      'Binary search on the *answer* — "is it possible to do it in k steps?" — is a different technique from binary search over data, and it is the harder one.',
    ],
    questions: [
      {
        id: 'ib-square-root-of-a-number',
        title: 'Square Root of a Number',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/square-root-of-a-number/',
      },
      {
        id: 'lc-binary-search',
        title: 'Binary Search',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/binary-search/',
      },
      {
        id: 'lc-search-insert-position',
        title: 'Search Insert Position',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/search-insert-position/',
      },
      {
        id: 'ib-search-in-rotated-array',
        title: 'Search in Rotated Array',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/search-in-rotated-array/',
      },
      {
        id: 'lc-find-minimum-in-rotated-sorted-array',
        title: 'Find Minimum in Rotated Sorted Array',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
      },
      {
        id: 'lc-search-in-rotated-sorted-array',
        title: 'Search in Rotated Sorted Array',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
      },
      {
        id: 'lc-kth-smallest-element-in-a-sorted-matrix',
        title: 'Kth Smallest Element in a Sorted Matrix',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/',
      },
      {
        id: 'gfg-egg-dropping-puzzle',
        title: 'Egg Dropping Puzzle',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/egg-dropping-puzzle/1',
      },
      {
        id: 'ib-woodcutting-made-easy',
        title: 'WoodCutting Made Easy',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/woodcutting-made-easy/',
      },
      {
        id: 'gfg-trailing-zeroes-in-factorial',
        title: 'Trailing Zeroes in Factorial',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/trailing-zeroes-in-factorial/1',
      },
      {
        id: 'lc-median-of-two-sorted-arrays',
        title: 'Median of Two Sorted Arrays',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
      },
      {
        id: 'he-easy-problem',
        title: 'Easy Problem',
        platform: 'hackerearth',
        level: 'hard',
        url: 'https://www.hackerearth.com/problem/algorithm/easy-problem/',
      },
    ],
  },

  {
    id: 'divide-and-conquer',
    title: 'Divide and conquer',
    blurb:
      'Split on the natural boundary, recurse, and combine. The combine step is where the pattern either earns its keep or quietly costs more than the split saved you.',
    phase: 'patterns',
    algoIds: ['merge-sort', 'quick-sort', 'counting-sort', 'radix-sort'],
    learnSlugs: ['divide-and-conquer', 'sorting-landscape'],
    keyPoints: [
      'The split has to be O(1) or O(log n) to be worth anything. A divide-and-conquer that copies both halves is just a slower loop.',
      'Merge sort pays O(n) per level and O(n log n) overall; the linear sorts pay O(n) only by not comparing.',
      'Quicksort is the same shape with a pivot instead of a midpoint, and its worst case is why randomised pivots exist.',
      'Counting sort is a divide-and-conquer with no recursion and no comparisons: it *counts* instead.',
    ],
    questions: [
      {
        id: 'hr-quicksort1',
        title: 'Quicksort 1 — Partition',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/quicksort1/problem',
      },
      {
        id: 'gfg-bubble-sort',
        title: 'Bubble Sort',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/bubble-sort/1',
      },
      {
        id: 'hr-almost-sorted-interval',
        title: 'Almost sorted interval',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/almost-sorted-interval/problem',
      },
      {
        id: 'ib-merge-two-sorted-arrays',
        title: 'Merge Two Sorted Arrays',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/merge-two-sorted-arrays/',
      },
      {
        id: 'lc-merge-two-sorted-lists',
        title: 'Merge Two Sorted Lists',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
      },
      {
        id: 'gfg-merge-two-sorted-linked-lists',
        title: 'Merge Two Sorted Linked Lists',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1',
      },
      {
        id: 'hr-merge-two-sorted-linked-lists',
        title: 'Merge two sorted linked lists',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/merge-two-sorted-linked-lists/problem',
      },
      {
        id: 'lc-merge-k-sorted-lists',
        title: 'Merge k Sorted Lists',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
      },
    ],
  },

  {
    id: 'linked-lists',
    title: 'Linked lists',
    blurb:
      'The first structure where position is not addressable. Everything about lists is a consequence of that: you cannot index, so you walk; you cannot random-access, so you need a slow pointer and a fast one.',
    phase: 'patterns',
    algoIds: ['reverse-list', 'merge-two-sorted', 'detect-cycle', 'hash-table'],
    learnSlugs: ['pointer-problems', 'recursion-is-a-stack'],
    keyPoints: [
      'Every traversal question is the same first question: can I use a second pointer? Fast/slow gives cycle detection and the middle node.',
      'Save the next pointer before you rewrite `curr.next`, or you have lost the rest of the list. This is the bug everyone writes once.',
      'A dummy head node removes every "what if the answer is the first element" branch. Use it by default.',
      'When a problem asks about a linked list, ask whether a *stack* would be simpler — reversing into a list, or postorder traversal, is often the intended answer.',
    ],
    questions: [
      {
        id: 'ib-reverse-list',
        title: 'Reverse List',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/reverse-list/',
      },
      {
        id: 'hr-reverse-a-linked-list',
        title: 'Reverse a linked list',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/reverse-a-linked-list/problem',
      },
      {
        id: 'gfg-reverse-a-linked-list',
        title: 'Reverse a Linked List',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1',
      },
      {
        id: 'lc-reverse-linked-list',
        title: 'Reverse Linked List',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/reverse-linked-list/',
      },
      {
        id: 'hr-find-the-merge-point-of-two-joined-linked-lists',
        title: 'Find Merge Point of Two Lists',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/find-the-merge-point-of-two-joined-linked-lists/problem',
      },
      {
        id: 'ib-detect-cycle',
        title: 'Detect Cycle',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/detect-cycle/',
      },
      {
        id: 'lc-linked-list-cycle',
        title: 'Linked List Cycle',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/linked-list-cycle/',
      },
      {
        id: 'hr-detect-whether-a-linked-list-contains-a-cycle',
        title: 'Cycle Detection',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/detect-whether-a-linked-list-contains-a-cycle/problem',
      },
      {
        id: 'ib-kth-from-end-list',
        title: 'Kth from End List',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/kth-from-end-list/',
      },
      {
        id: 'lc-remove-nth-node-from-end',
        title: 'Remove Nth Node From End of List',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
      },
      {
        id: 'ib-intersection-of-linked-lists',
        title: 'Intersection of Linked Lists',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/intersection-of-linked-lists/',
      },
      {
        id: 'lc-intersection-of-two-linked-lists',
        title: 'Intersection of Two Linked Lists',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
      },
      {
        id: 'ib-palindrome-list',
        title: 'Palindrome List',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/palindrome-list/',
      },
      {
        id: 'lc-palindrome-linked-list',
        title: 'Palindrome Linked List',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/palindrome-linked-list/',
      },
      {
        id: 'gfg-delete-middle-of-linked-list',
        title: 'Delete Middle of Linked List',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/delete-middle-of-linked-list/1',
      },
      {
        id: 'ib-add-two-numbers',
        title: 'Add Two Numbers',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/add-two-numbers/',
      },
      {
        id: 'lc-add-two-numbers',
        title: 'Add Two Numbers',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/add-two-numbers/',
      },
      {
        id: 'lc-middle-of-the-linked-list',
        title: 'Middle of the Linked List',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/middle-of-the-linked-list/',
      },
      {
        id: 'lc-reorder-list',
        title: 'Reorder List',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/reorder-list/',
      },
      {
        id: 'ib-remove-cycle-from-linked-list',
        title: 'Remove Cycle from Linked List',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/remove-cycle-from-linked-list/',
      },
      {
        id: 'hr-compare-two-linked-lists',
        title: 'Compare two linked lists',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/compare-two-linked-lists/problem',
      },
      {
        id: 'hr-insert-a-node-at-a-specific-position-in-a-linked-list',
        title: 'Insert a node at a specific position in a linked list',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/insert-a-node-at-a-specific-position-in-a-linked-list/problem',
      },
      {
        id: 'lc-copy-list-with-random-pointer',
        title: 'Copy List with Random Pointer',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
      },
      {
        id: 'lc-convert-sorted-list-to-bst',
        title: 'Convert Sorted List to Binary Search Tree',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/',
      },
    ],
  },

  {
    id: 'stacks-and-queues',
    title: 'Stacks and queues',
    blurb:
      'Structures that remember for you. A stack answers "what was the most recent unmatched thing?" and a queue answers "what came next?" — which is why balanced brackets, next-greater elements, and BFS are all one idea wearing different hats.',
    phase: 'patterns',
    algoIds: ['balanced-brackets', 'valid-postfix', 'min-stack', 'next-greater-element'],
    learnSlugs: ['monotonic-stack', 'recursion-is-a-stack'],
    keyPoints: [
      'Push to solve, pop to answer. When a bracket does not match, the top of the stack is the answer and nothing else is needed.',
      'A monotonic stack answers "the nearest greater/smaller element to my left or right" in one pass. Learn this one; it is the most reused idea in the topic.',
      'A queue is the structure BFS uses and a stack is the structure DFS uses. If the question is "shortest path in an unweighted graph", it is a queue.',
      'Two stacks make a queue and a queue with a running sum makes a sliding window maximum. Both are worth writing once by hand.',
    ],
    questions: [
      {
        id: 'lc-valid-parentheses',
        title: 'Valid Parentheses',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/valid-parentheses/',
      },
      {
        id: 'hr-balanced-brackets',
        title: 'Balanced Brackets',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/balanced-brackets/problem',
      },
      {
        id: 'lc-next-greater-element-i',
        title: 'Next Greater Element I',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/next-greater-element-i/',
      },
      {
        id: 'gfg-next-greater-element',
        title: 'Next Greater in Circular Array',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/next-greater-element/1',
      },
      {
        id: 'lc-daily-temperatures',
        title: 'Daily Temperatures',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/daily-temperatures/',
      },
      {
        id: 'lc-evaluate-reverse-polish-notation',
        title: 'Evaluate Reverse Polish Notation',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
      },
      {
        id: 'lc-decode-string',
        title: 'Decode String',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/decode-string/',
      },
      {
        id: 'gfg-decode-the-string',
        title: 'Decode the String',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/decode-the-string/1',
      },
      {
        id: 'hr-queue-using-two-stacks',
        title: 'Queue using Two Stacks',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/queue-using-two-stacks/problem',
      },
      {
        id: 'hr-maximum-element',
        title: 'Maximum Element',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/maximum-element/problem',
      },
      {
        id: 'hr-equal-stacks',
        title: 'Equal Stacks',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/equal-stacks/problem',
      },
      {
        id: 'lc-largest-rectangle-in-histogram',
        title: 'Largest Rectangle in Histogram',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
      },
      {
        id: 'gfg-trapping-rain-water',
        title: 'Trapping Rain Water',
        platform: 'gfg',
        level: 'hard',
        url: 'https://www.geeksforgeeks.org/problems/trapping-rain-water/1',
      },
      {
        id: 'lc-basic-calculator',
        title: 'Basic Calculator',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/basic-calculator/',
      },
    ],
  },

  {
    id: 'recursion-and-backtracking',
    title: 'Recursion and backtracking',
    blurb:
      'Recursion is a stack you did not allocate. Backtracking is recursion plus the discipline of undoing your choice — and the discipline is the whole difficulty, because the bug is almost never forgetting to undo.',
    phase: 'patterns',
    algoIds: ['tower-of-hanoi'],
    learnSlugs: ['recursion-is-a-stack', 'divide-and-conquer'],
    keyPoints: [
      'Every recursion needs three things: a base case, a smaller instance, and a move from one to the other. Write the base case first.',
      'Backtracking is *choose*, *recurse*, *undo*, in that order, at every level. The undo is what makes it a search.',
      'Track the current path explicitly. Passing a mutated array down and trusting yourself to repair it is how exponential blowups become wrong answers.',
      'The classic failures: forgetting the undo, using `==` to compare two element lists in JS, and an off-by-one that makes the base case unreachable.',
    ],
    questions: [
      {
        id: 'lc-subsets',
        title: 'Subsets',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/subsets/',
      },
      {
        id: 'lc-permutations',
        title: 'Permutations',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/permutations/',
      },
      {
        id: 'lc-combination-sum',
        title: 'Combination Sum',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/combination-sum/',
      },
      {
        id: 'gfg-combination-sum',
        title: 'Target Sum Combinations',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/combination-sum/1',
      },
      {
        id: 'lc-letter-combinations-of-a-phone-number',
        title: 'Letter Combinations of a Phone Number',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
      },
      {
        id: 'lc-word-search',
        title: 'Word Search',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/word-search/',
      },
      {
        id: 'gfg-word-search',
        title: 'Word Search',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/word-search/1',
      },
      {
        id: 'ib-word-search-ii',
        title: 'Word Search II',
        platform: 'interviewbit',
        level: 'hard',
        url: 'https://www.interviewbit.com/problems/word-search-ii/',
      },
      {
        id: 'lc-word-search-ii',
        title: 'Word Search II',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/word-search-ii/',
      },
      {
        id: 'hr-ctci-fibonacci-numbers',
        title: 'Recursion: Fibonacci Numbers',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem',
      },
      {
        id: 'lc-restore-ip-addresses',
        title: 'Restore IP Addresses',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/restore-ip-addresses/',
      },
      {
        id: 'lc-sudoku-solver',
        title: 'Sudoku Solver',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/sudoku-solver/',
      },
    ],
  },
] as const;
