import type { Topic } from '../types.ts';

/**
 * Phase 3 — Structures.
 *
 * ## Trees before graphs, and graphs last on purpose
 *
 * A tree *is* a graph — it is the one special case, and treating it as a general
 * graph is why graph questions feel harder than they are. Doing trees first lets the
 * recursive shape (node + child subtrees) become automatic before the learner has to
 * hold recursion, a visited set, a queue, and the algorithm at the same time.
 *
 * ## Greedy is placed *after* trees, not before
 *
 * Counter-intuitive, and the ordering matters. A greedy answer is a claim: "taking
 * the locally best step cannot hurt." That claim is only checkable once you can
 * reason about a recursive search space, because the thing you are skipping is the
 * alternative branch. Taught right after sliding window it becomes a template to
 * memorise; taught here, it is something you can argue for.
 *
 * ## Bit manipulation and maths sit in this phase, not the first one
 *
 * They need loops, conditionals and exponentiation to be boring, and they need
 * enough structure awareness to be interesting. Putting them in the foundation would
 * mean either trivial problems or arithmetic dressed up as data structures.
 */
export const STRUCTURES: readonly Topic[] = [
  {
    id: 'maths-and-bit-manipulation',
    title: 'Maths and bit manipulation',
    blurb:
      'The questions that are not really data-structure questions at all. They look like puzzles, they are checked by an exact verdict rather than a test case, and they reward knowing one standard trick each.',
    phase: 'structures',
    algoIds: [],
    learnSlugs: [],
    keyPoints: [
      'Modulo keeps numbers small. If the answer is huge, it is always asked for mod m — take the modulus at every step, not at the end.',
      'Know the bit vocabulary: a mask to test a bit, a shift to move one, XOR to toggle or to compare two sets, and `x & (x-1)` to drop the lowest set bit.',
      'Number theory worth memorising: Fermat for modular inverses, the sieve of Eratosthenes for primes, and the trailing-zeroes trick (count factors of 5, not 2).',
      'Overflow is a real failure mode. In C-family languages, `long` is 64-bit but an `int` literal pair multiplied first may not be.',
    ],
    questions: [
      {
        id: 'cc-flow004',
        title: 'FLOW004 — First and Last Digit',
        platform: 'codechef',
        level: 'easy',
        url: 'https://www.codechef.com/problems/FLOW004',
      },
      {
        id: 'cc-flow005',
        title: 'FLOW005 — Smallest Numbers of Notes',
        platform: 'codechef',
        level: 'easy',
        url: 'https://www.codechef.com/problems/FLOW005',
      },
      {
        id: 'cc-flow016',
        title: 'FLOW016 — GCD and LCM',
        platform: 'codechef',
        level: 'easy',
        url: 'https://www.codechef.com/problems/FLOW016',
      },
      {
        id: 'cc-flow017',
        title: 'FLOW017 — Second Largest',
        platform: 'codechef',
        level: 'easy',
        url: 'https://www.codechef.com/problems/FLOW017',
      },
      {
        id: 'cc-flow021',
        title: 'FLOW021 — Primes',
        platform: 'codechef',
        level: 'easy',
        url: 'https://www.codechef.com/problems/FLOW021',
      },
      {
        id: 'lc-number-of-1-bits',
        title: 'Number of 1 Bits',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/number-of-1-bits/',
      },
      {
        id: 'lc-counting-bits',
        title: 'Counting Bits',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/counting-bits/',
      },
      {
        id: 'lc-reverse-bits',
        title: 'Reverse Bits',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/reverse-bits/',
      },
      {
        id: 'lc-sum-of-two-integers',
        title: 'Sum of Two Integers',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/sum-of-two-integers/',
      },
      {
        id: 'ib-flip-bits',
        title: 'Flip Bits',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/flip-bits/',
      },
      {
        id: 'ib-count-1-in-a-binary-string',
        title: 'Count 1 in a Binary String',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/count-1-in-a-binary-string/',
      },
      {
        id: 'hr-flipping-bits',
        title: 'Flipping bits',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/flipping-bits/problem',
      },
      {
        id: 'hr-and-product',
        title: 'AND Product',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/and-product/problem',
      },
      {
        id: 'hr-the-great-xor',
        title: 'The Great XOR',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/the-great-xor/problem',
      },
      {
        id: 'hr-best-divisor',
        title: 'Best Divisor',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/best-divisor/problem',
      },
      {
        id: 'hr-divisor-exploration',
        title: 'Divisor Exploration',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/divisor-exploration/problem',
      },
      {
        id: 'hr-manasa-and-factorials',
        title: 'Manasa and Factorials',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/manasa-and-factorials/problem',
      },
      {
        id: 'hr-cube-summation',
        title: 'Cube Summation',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/cube-summation/problem',
      },
      {
        id: 'hr-prime-date',
        title: 'Prime Dates',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/prime-date/problem',
      },
      {
        id: 'lc-sqrtx',
        title: 'Sqrt(x)',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/sqrtx/',
      },
      {
        id: 'lc-powx-n',
        title: 'Pow(x, n)',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/powx-n/',
      },
      {
        id: 'hr-construct-the-array',
        title: 'Construct the Array',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/construct-the-array/problem',
      },
      {
        id: 'ib-equal',
        title: 'Equal',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/equal/',
      },
      {
        id: 'he-monk-and-his-love-for-primes',
        title: 'Monk and his love for primes',
        platform: 'hackerearth',
        level: 'medium',
        url: 'https://www.hackerearth.com/problem/algorithm/monk-and-his-love-for-primes/',
      },
      {
        id: 'he-divisibility',
        title: 'Divisibility',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/divisibility/',
      },
      {
        id: 'he-tuples',
        title: 'Tuples',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/tuples/',
      },
    ],
  },

  {
    id: 'trees-and-bst',
    title: 'Trees and BSTs',
    blurb:
      'A node and its subtrees. Almost every tree problem is one of four walks — preorder, inorder, postorder, level order — plus an invariant that says what the walk is *for*.',
    phase: 'structures',
    algoIds: [
      'inorder-traversal',
      'tree-height',
      'bst-search',
      'bst-insert',
      'bst-delete',
      'avl-rotate',
    ],
    learnSlugs: ['binary-search-trees', 'bfs-and-dfs'],
    keyPoints: [
      'Inorder on a BST is sorted. That single fact is what makes a BST useful, and what makes "validate BST" a bounds problem rather than a comparison problem.',
      'Recursive definition, recursive solution: every tree function is `f(node)` in terms of `f(node.left)` and `f(node.right)`.',
      'Know the three recursive invariants: a path length, a subtree aggregate, and a global that the recursion updates as it unwinds.',
      'Height matters for the complexity of everything below it. A balanced BST is O(log n); an unbalanced one is O(n) and lies about it.',
    ],
    questions: [
      {
        id: 'hr-tree-inorder-traversal',
        title: 'Tree: Inorder Traversal',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/tree-inorder-traversal/problem',
      },
      {
        id: 'hr-tree-preorder-traversal',
        title: 'Tree: Preorder Traversal',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/tree-preorder-traversal/problem',
      },
      {
        id: 'hr-tree-postorder-traversal',
        title: 'Tree: Postorder Traversal',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/tree-postorder-traversal/problem',
      },
      {
        id: 'hr-tree-level-order-traversal',
        title: 'Tree: Level Order Traversal',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/tree-level-order-traversal/problem',
      },
      {
        id: 'gfg-preorder-traversal',
        title: 'Preorder Traversal',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/preorder-traversal/1',
      },
      {
        id: 'gfg-postorder-traversal',
        title: 'Postorder Traversal',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/postorder-traversal/1',
      },
      {
        id: 'lc-same-tree',
        title: 'Same Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/same-tree/',
      },
      {
        id: 'ib-identical-binary-trees',
        title: 'Identical Binary Trees',
        platform: 'interviewbit',
        level: 'easy',
        url: 'https://www.interviewbit.com/problems/identical-binary-trees/',
      },
      {
        id: 'lc-maximum-depth-of-binary-tree',
        title: 'Maximum Depth of Binary Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
      },
      {
        id: 'lc-invert-binary-tree',
        title: 'Invert Binary Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/invert-binary-tree/',
      },
      {
        id: 'gfg-mirror-tree',
        title: 'Convert to Mirror Tree',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/mirror-tree/1',
      },
      {
        id: 'lc-symmetric-tree',
        title: 'Symmetric Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/symmetric-tree/',
      },
      {
        id: 'gfg-symmetric-tree',
        title: 'Symmetric Tree',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/symmetric-tree/1',
      },
      {
        id: 'lc-validate-binary-search-tree',
        title: 'Validate Binary Search Tree',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/validate-binary-search-tree/',
      },
      {
        id: 'gfg-inorder-successor-in-bst',
        title: 'Inorder Successor in BST',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/inorder-successor-in-bst/1',
      },
      {
        id: 'lc-kth-smallest-element-in-a-bst',
        title: 'Kth Smallest Element in a BST',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
      },
      {
        id: 'hr-is-binary-search-tree',
        title: 'Is This a Binary Search Tree?',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/is-binary-search-tree/problem',
      },
      {
        id: 'lc-lowest-common-ancestor-of-a-bst',
        title: 'Lowest Common Ancestor of a BST',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
      },
      {
        id: 'gfg-lowest-common-ancestor-in-a-binary-tree',
        title: 'LCA in a Binary Tree',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1',
      },
      {
        id: 'lc-diameter-of-binary-tree',
        title: 'Diameter of Binary Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/diameter-of-binary-tree/',
      },
      {
        id: 'gfg-diameter-of-binary-tree',
        title: 'Diameter of Binary Tree',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1',
      },
      {
        id: 'gfg-height-of-binary-tree',
        title: 'Height of Binary Tree',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/height-of-binary-tree/1',
      },
      {
        id: 'hr-tree-height-of-a-binary-tree',
        title: 'Tree: Height of a Binary Tree',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/tree-height-of-a-binary-tree/problem',
      },
      {
        id: 'hr-even-tree',
        title: 'Even Tree',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/even-tree/problem',
      },
      {
        id: 'hr-cut-the-tree',
        title: 'Cut the Tree',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/cut-the-tree/problem',
      },
      {
        id: 'lc-path-sum',
        title: 'Path Sum',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/path-sum/',
      },
      {
        id: 'lc-sum-of-left-leaves',
        title: 'Sum of Left Leaves',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/sum-of-left-leaves/',
      },
      {
        id: 'ib-maximum-path-sum',
        title: 'Maximum Path Sum',
        platform: 'interviewbit',
        level: 'hard',
        url: 'https://www.interviewbit.com/problems/maximum-path-sum/',
      },
      {
        id: 'lc-balanced-binary-tree',
        title: 'Balanced Binary Tree',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/balanced-binary-tree/',
      },
      {
        id: 'lc-serialize-and-deserialize-binary-tree',
        title: 'Serialize and Deserialize Binary Tree',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
      },
      {
        id: 'lc-construct-binary-tree',
        title: 'Construct Binary Tree from Preorder and Inorder Traversal',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
      },
      {
        id: 'lc-binary-tree-right-side-view',
        title: 'Binary Tree Right Side View',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/binary-tree-right-side-view/',
      },
      {
        id: 'hr-lexicographic-steps',
        title: 'Lexicographic paths',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/lexicographic-steps/problem',
      },
      {
        id: 'he-the-grass-type',
        title: 'The Grass Type',
        platform: 'hackerearth',
        level: 'hard',
        url: 'https://www.hackerearth.com/problem/algorithm/the-grass-type/',
      },
    ],
  },

  {
    id: 'heaps-and-priority-queues',
    title: 'Heaps and priority queues',
    blurb:
      'A structure that gives you the extremes for free. Once you reach for it, a question that was "find the k-th best thing" becomes "run k steps of a loop", and the complexity drops from O(n log n) to O(n + k log n).',
    phase: 'structures',
    algoIds: ['build-heap', 'heapsort'],
    learnSlugs: ['heaps'],
    keyPoints: [
      'A heap only promises the top. Everything below it is unordered, which is why it cannot answer range queries and why you cannot index into it.',
      'Every stream problem has a heap answer: k-largest, median of a stream, merging sorted runs, scheduling by priority.',
      'Heapify is O(n), not O(n log n). Building a heap by repeated push is a beginner mistake that costs a log factor.',
      'Hash + heap is the general answer: a heap to order, a map to count. Bishu and Soldiers is the canonical shape.',
    ],
    questions: [
      {
        id: 'lc-last-stone-weight',
        title: 'Last Stone Weight',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/last-stone-weight/',
      },
      {
        id: 'gfg-kth-smallest-element-heap',
        title: 'Kth Smallest',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/kth-smallest-element/1',
      },
      {
        id: 'lc-kth-largest-element-in-an-array',
        title: 'Kth Largest Element in an Array',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
      },
      {
        id: 'hr-jim-and-the-orders',
        title: 'Jim and the Orders',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/jim-and-the-orders/problem',
      },
      {
        id: 'lc-find-median-from-data-stream',
        title: 'Find Median from Data Stream',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/find-median-from-data-stream/',
      },
      {
        id: 'he-monk-and-the-magical-candy-bags',
        title: 'Monk and the Magical Candy Bags',
        platform: 'hackerearth',
        level: 'medium',
        url: 'https://www.hackerearth.com/problem/algorithm/monk-and-the-magical-candy-bags/',
      },
      {
        id: 'gfg-job-sequencing-problem',
        title: 'Job Sequencing Problem',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/job-sequencing-problem/1',
      },
      {
        id: 'he-bishu-and-soldiers',
        title: 'Bishu and Soldiers',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/bishu-and-soldiers/',
      },
      {
        id: 'he-puchi-and-luggage',
        title: 'Puchi and Luggage',
        platform: 'hackerearth',
        level: 'hard',
        url: 'https://www.hackerearth.com/problem/algorithm/puchi-and-luggage/',
      },
    ],
  },

  {
    id: 'tries-and-prefix-queries',
    title: 'Tries and prefix queries',
    blurb:
      'One narrow data structure that answers "does any word start with this?" in time proportional to the query, not the dictionary. You will meet it twice: once as a prefix tree, once as the same idea inside Aho-Corasick.',
    phase: 'structures',
    algoIds: ['trie'],
    learnSlugs: ['strings-as-keys'],
    keyPoints: [
      'A trie is a tree of characters. Cost is O(length of the key), independent of how many keys you stored.',
      'Reach for a trie when the question is about *prefixes*, not about exact lookups — a hash map cannot do "find all keys starting with ab".',
      'The alphabet decides the node size. A 26-pointer array per node is simple and fast; a map per node is smaller and fine in practice.',
      'If you only need one pass of lookups, a sorted array plus binary search does the same job with far less code. Know both.',
    ],
    questions: [
      {
        id: 'hr-prefix-compression',
        title: 'Prefix Compression',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/prefix-compression/problem',
      },
      {
        id: 'lc-implement-trie-prefix-tree',
        title: 'Implement Trie (Prefix Tree)',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
      },
      {
        id: 'hr-no-prefix-set',
        title: 'No Prefix Set',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/no-prefix-set/problem',
      },
      {
        id: 'he-monk-and-his-friends',
        title: 'Monk and his Friends',
        platform: 'hackerearth',
        level: 'medium',
        url: 'https://www.hackerearth.com/problem/algorithm/monk-and-his-friends/',
      },
      {
        id: 'lc-design-add-and-search-words',
        title: 'Design Add and Search Words Data Structure',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
      },
      {
        id: 'hr-string-similarity',
        title: 'String Similarity',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/string-similarity/problem',
      },
      {
        id: 'he-roy-and-cipher-disk',
        title: 'Roy and Cipher Disk',
        platform: 'hackerearth',
        level: 'medium',
        url: 'https://www.hackerearth.com/problem/algorithm/roy-and-cipher-disk/',
      },
    ],
  },

  {
    id: 'graphs-bfs-dfs',
    title: 'Graphs: BFS and DFS',
    blurb:
      'The point where the input stops being a list of things and becomes a set of things with relationships. BFS answers shortest path; DFS answers "what can I reach" and "what can I form".',
    phase: 'structures',
    algoIds: ['bfs', 'dfs', 'flood-fill', 'number-of-islands'],
    learnSlugs: ['bfs-and-dfs', 'traversal-in-practice'],
    keyPoints: [
      'BFS with a queue gives the shortest path in an unweighted graph. DFS with a stack does not — that difference is the whole reason both exist.',
      'The `visited` set is not optional and it must be marked on *enqueue*, not on dequeue. Marking late is the classic infinite loop.',
      'Write down the graph as nodes and edges *before* writing any code. If you cannot draw it, you do not understand the problem yet.',
      'Grid problems are graphs. A cell is a node and its neighbours are its edges — that reframing turns dozens of grid problems into BFS/DFS.',
    ],
    questions: [
      {
        id: 'he-bfs',
        title: 'BFS',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/bfs/',
      },
      {
        id: 'gfg-bfs-traversal-of-graph',
        title: 'BFS of Graph',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/bfs-traversal-of-graph/1',
      },
      {
        id: 'he-micro-and-maze',
        title: 'Micro and Maze',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/micro-and-maze/',
      },
      {
        id: 'hr-connected-cell-in-a-grid',
        title: 'Connected Cells in a Grid',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/connected-cell-in-a-grid/problem',
      },
      {
        id: 'hr-grid-challenge',
        title: 'Grid Challenge',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/grid-challenge/problem',
      },
      {
        id: 'he-a-walk-to-remember',
        title: 'A Walk to Remember',
        platform: 'hackerearth',
        level: 'easy',
        url: 'https://www.hackerearth.com/problem/algorithm/a-walk-to-remember/',
      },
      {
        id: 'lc-flood-fill',
        title: 'Flood Fill',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/flood-fill/',
      },
      {
        id: 'lc-clone-graph',
        title: 'Clone Graph',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/clone-graph/',
      },
      {
        id: 'ib-clone-graph',
        title: 'Clone Graph',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/clone-graph/',
      },
      {
        id: 'lc-number-of-islands',
        title: 'Number of Islands',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/number-of-islands/',
      },
      {
        id: 'ib-number-of-islands',
        title: 'Number of Islands',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/number-of-islands/',
      },
      {
        id: 'gfg-number-of-islands',
        title: 'Count Islands After Every Operation',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/number-of-islands/1',
      },
      {
        id: 'lc-surrounded-regions',
        title: 'Surrounded Regions',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/surrounded-regions/',
      },
      {
        id: 'ib-surrounded-regions',
        title: 'Surrounded Regions',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/surrounded-regions/',
      },
      {
        id: 'lc-pacific-atlantic-water-flow',
        title: 'Pacific Atlantic Water Flow',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
      },
      {
        id: 'hr-castle-on-the-grid',
        title: 'Castle on the Grid',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/castle-on-the-grid/problem',
      },
      {
        id: 'lc-regions-cut-by-slashes',
        title: 'Regions Cut By Slashes',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/regions-cut-by-slashes/',
      },
    ],
  },

  {
    id: 'greedy-and-intervals',
    title: 'Greedy, intervals and scheduling',
    blurb:
      'Take the best-looking step now, and prove the step cannot hurt. The proof is the actual skill — a greedy solution with no exchange argument is a guess with good test-case luck.',
    phase: 'structures',
    algoIds: ['activity-selection', 'gas-station', 'jump-game-2'],
    learnSlugs: ['greedy'],
    keyPoints: [
      'The exchange argument: show that any optimal solution can be changed to include your greedy choice without getting worse. If you cannot say it, you have not justified it.',
      'Sorting by end time solves interval scheduling and interval colouring. Sorting by start time solves "what am I doing now" queries.',
      'Two pointers after sorting is the standard interval move. Three nested loops over intervals is almost always a missed sort.',
      'Greedy fails when choices interact — usually when a later choice restricts an earlier one. That is your cue to switch to DP.',
    ],
    questions: [
      {
        id: 'gfg-activity-selection',
        title: 'Activity Selection',
        platform: 'gfg',
        level: 'easy',
        url: 'https://www.geeksforgeeks.org/problems/activity-selection/1',
      },
      {
        id: 'lc-non-overlapping-intervals',
        title: 'Non-overlapping Intervals',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/non-overlapping-intervals/',
      },
      {
        id: 'lc-insert-interval',
        title: 'Insert Interval',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/insert-interval/',
      },
      {
        id: 'lc-interval-list-intersections',
        title: 'Interval List Intersections',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/interval-list-intersections/',
      },
      {
        id: 'gfg-minimum-number-of-jumps',
        title: 'Minimum Jumps',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/minimum-number-of-jumps/1',
      },
      {
        id: 'lc-jump-game',
        title: 'Jump Game',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/jump-game/',
      },
      {
        id: 'lc-jump-game-ii',
        title: 'Jump Game II',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/jump-game-ii/',
      },
      {
        id: 'hr-kangaroo',
        title: 'Number Line Jumps',
        platform: 'hackerrank',
        level: 'easy',
        url: 'https://www.hackerrank.com/challenges/kangaroo/problem',
      },
      {
        id: 'lc-gas-station',
        title: 'Gas Station',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/gas-station/',
      },
      {
        id: 'ib-allocate-books',
        title: 'Allocate Books',
        platform: 'interviewbit',
        level: 'medium',
        url: 'https://www.interviewbit.com/problems/allocate-books/',
      },
      {
        id: 'lc-candy',
        title: 'Candy',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/candy/',
      },
      {
        id: 'lc-assign-cookies',
        title: 'Assign Cookies',
        platform: 'leetcode',
        level: 'easy',
        url: 'https://leetcode.com/problems/assign-cookies/',
      },
      {
        id: 'lc-partition-labels',
        title: 'Partition Labels',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/partition-labels/',
      },
      {
        id: 'lc-task-scheduler',
        title: 'Task Scheduler',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/task-scheduler/',
      },
      {
        id: 'hr-the-indian-job',
        title: 'The Indian Job',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/the-indian-job/problem',
      },
      {
        id: 'hr-angry-children-2',
        title: 'Angry Children 2',
        platform: 'hackerrank',
        level: 'hard',
        url: 'https://www.hackerrank.com/challenges/angry-children-2/problem',
      },
      {
        id: 'lc-minimum-number-of-refueling-stops',
        title: 'Minimum Number of Refueling Stops',
        platform: 'leetcode',
        level: 'hard',
        url: 'https://leetcode.com/problems/minimum-number-of-refueling-stops/',
      },
      {
        id: 'hr-closest-number',
        title: 'Closest Number',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/closest-number/problem',
      },
      {
        id: 'gfg-fractional-knapsack',
        title: 'Fractional Knapsack',
        platform: 'gfg',
        level: 'medium',
        url: 'https://www.geeksforgeeks.org/problems/fractional-knapsack/1',
      },
      {
        id: 'cc-tachstck',
        title: 'TACHSTCK — Chopsticks',
        platform: 'codechef',
        level: 'hard',
        url: 'https://www.codechef.com/problems/TACHSTCK',
      },
      {
        id: 'hr-climbing-the-leaderboard',
        title: 'Climbing the Leaderboard',
        platform: 'hackerrank',
        level: 'medium',
        url: 'https://www.hackerrank.com/challenges/climbing-the-leaderboard/problem',
      },
      {
        id: 'lc-asteroid-collision',
        title: 'Asteroid Collision',
        platform: 'leetcode',
        level: 'medium',
        url: 'https://leetcode.com/problems/asteroid-collision/',
      },
    ],
  },
] as const;
